### ISSUE TITLE
signed CLA, but status checking filed in PR

### ISSUE THREAD

**Issue by triThirty** [cla-assistant/cla-assistant#1009]
<img width="992" alt="image" src="https://github.com/cla-assistant/cla-assistant/assets/10457955/ebf9369c-e68a-4342-935a-8ffec810fcb3">
I have signed CLA, but in PR, it shows pending

https://github.com/SAP/jenkins-library/pull/4468 

<img width="845" alt="image" src="https://github.com/cla-assistant/cla-assistant/assets/10457955/b5550e0e-2280-40bd-8a14-bf0a2a898e71">

**Comment by Shegox** [comment]
Hi, 

two out of the three commits are created by `bruce.mao@sap.com` (https://github.com/SAP/jenkins-library/commit/4f8ae6e2c42eb0431cbb8fa85d153730d5ccae00.patch, https://github.com/SAP/jenkins-library/commit/3b76435290a5918ffb43c9311f4e5e017c6c323d.patch) and that's why the PR is still pending. 

All authors need to sign the CLA for it to be accepted into the project. `bruce.mao@sap.com` additionally doesn't seem to be associated with any GitHub account. If that is your email, please just add them to your GitHub account (https://github.com/settings/emails) and then trigger a recheck. If that is not your email, please ask them to sign the CLA.

**Comment by triThirty** [comment]
Hi,
I added bruce.mao@sap.com my github account, but how can I trigger a recheck?

**Comment by Shegox** [comment]
At the end of the CLA comment there is a link for rechecking: 
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/jenkins-library?pullRequest=4468) it.

I already triggered that and now the CLA shows signed and the check passes.
