### ISSUE TITLE
I signed the CLA but I still can't merge pull requests

### ISSUE THREAD

**Issue by alexaytov** [cla-assistant/cla-assistant#1067]
Here is the pull request: https://github.com/SAP-samples/automation-pilot-examples/pull/105

When I agree to the CLA I see this text: `You have agreed to the CLA for SAP-samples/automation-pilot-examples
` and I am redirected back to github but the PR is not updated. I've tried to click on the recheck link from the comment but nothing happens.

**Comment by Shegox** [comment]
Looking [at the commits](https://github.com/SAP-samples/automation-pilot-examples/commit/d4c987174cc0397677d5279e7b3ca10a9d21f597.patch) it seems that the commit author is `<aleksandar.aytov@sap.com>` is associated with the github.com account (aleks-aytov) instead of the PR author account ([alexaytov](https://github.com/alexaytov)).

Please either add the email to your PR user or additionally sign the CLA with the github account which authored the commit (aleks-aytov).

**Comment by alexaytov** [comment]
Yes, that was the issue. Thank you very much!
