### ISSUE TITLE
License check pends forever in PR after signing CLA (even after trying fixes suggested by similar issues)

### ISSUE THREAD

**Issue by renesas-abigail** [cla-assistant/cla-assistant#1076]
## URL to the linked Repository or Organization

Organization: https://github.com/renesas/fsp/

PR that is forever pending on status check: https://github.com/renesas/fsp/pull/372

## Steps to reproduce the problem

1. Open PR to linked repository 
2. Commit changes with github noreply email address
3. Sign the CLA

## What is the expected result?

The status check completes

## What happens instead?

CLA bot comment says "All committers have signed the CLA." but status check pends forever with message "Some checks haven’t completed yet.".

## Any other information? (attach screenshot if possible)

* I tried the following based on similar issues I found searching Github
  * **Recheck PR link**: https://cla-assistant.io/check/renesas/fsp?pullRequest=372
  * **Confirm committer email matches Github account email**: I commit with 138502477+renesas-abigail@users.noreply.github.com, which is generated from my real email because I use the email privacy feature of Github. When I try to add the noreply email in github settings -> emails -> add email address I get the error "Error adding 138502477+renesas-abigail@users.noreply.github.com: email is already in use  "so the email is definitely associated with my account.
  * **Make a change to the PR to retrigger the webhook** (I force pushed an amendment to the commit message)
  * Wait a few days

**Comment by renesas-abigail** [comment]
Sorry to bother you again, but is there anything you can see from your side that would explain why the status check is still pending? We are having difficulty troubleshooting it on our end but would like to be able to merge the pull request.

**Comment by KharitonOff** [comment]
I personally don't have access to the system anymore. But looking at the status (missing icon and links), it seems to me that the repository or organization owner has disconnected the CLA assistant (or maybe the webhook was removed), but the status enforcement is still set for the PullRequests.
You should ask the project admin to check the connection to the CLA assistant if they want to continue using it or remove the CLA status from branch protection, if not.

**Comment by renesas-abigail** [comment]
Hi, I verified the webhook is set up still and we want to continue using CLA assistant. Also it still shows up with green checkmarks in Integrations > Applications > Authorized OAuth apps, as expected.

Can you clarify the minimum required permissions for the account that linked the CLA assistant? Does it need to be a repository admin even after linking the CLA?

**Comment by KharitonOff** [comment]
Yes, that's correct. CLA assistant uses personal access tokens for the API calls, therefore the person needs to have admin rights (also after linking the repo).

**Comment by renesas-abigail** [comment]
Thank you for the information. I think to fix it, we need to move the CLA Assistant linkage to a different Github account. Because the current account can only temporarily have admin rights (for internal reasons). 

Can you comment on the steps that I believe are involved in moving the linkage to a different account? If it should work, if I have anything incorrect, etc.

1. Set current account to repository admin
2. Export existing signatures from CLA Assistant UI
3. Remove the status check requirement in the repository ruleset
4. From CLA Assistant UI, select unlink
    - Confirm webhook was removed, if its not removed, then remove it manually in Github UI
    - Confirm CLA assistant no longer shows in OAuth apps, otherwise revoke permissions manually
5. Delete the existing CLA Assistant comments on open PR's
6. On new admin account, set up CLA assistant like usual (same as first time setup)
7. Import old signatures into new CLA assistant
8. In CLA Assistant UI, use recheck PR's button to retrigger the bot on existing PR's
9. Add back the status check requirement in the repository ruleset

**Comment by KharitonOff** [comment]
You can follow the steps as planned. I think it would be sufficient to make steps 1,2,4,5 and 8

_1. Set current account to repository admin_  ✅ 
_2. Export existing signatures from CLA Assistant UI_ ✅ This is optional. If you re-link the repository with the same gist the signatures remain unchanged. But to be on the safe side, I would suggest exporting them.
_3. Remove the status check requirement in the repository ruleset_ ✅ Also optional if you continue using CLA assistant
_4. From CLA Assistant UI, select unlink_ ✅
_5. Confirm webhook was removed, if its not removed, then remove it manually in Github UI_ ✅
_6. Confirm CLA assistant no longer shows in OAuth apps, otherwise revoke permissions manually_ ❌ Not necessary, step 1 should be sufficient
_7. Delete the existing CLA Assistant comments on open PR's_ ❌ - no need for this, CLA assistant should handle existing comments and update them accordingly
_8. On new admin account, set up CLA assistant like usual (same as first time setup)_ ✅ yes, just make sure that you use the same CLA gist (url)
_9. Import old signatures into new CLA assistant_ ❌ only if something goes wrong and CLA assistant doesn't show you old signatures after relinking.
_10. In CLA Assistant UI, use recheck PR's button to retrigger the bot on existing PR's_ ❌ this should happen automatically, if the status doesn't get updated after couple of minutes (ideally 1 hour), then you can trigger a recheck. The APIs from GitHub have rate limits and it might happen that the number of calls needed to update the statuses of PRs exceed those.
_11. Add back the status check requirement in the repository ruleset_ ✅ Yes, if you decide to remove it in step 3

**Comment by renesas-abigail** [comment]
Thank you so much for your help! Everything is now working.

I will summarize this issue below in case it helps anyone else.

### Root cause of issue

The Github account that set up CLA Assistant had its permissions changed from admin -> read after linking the CLA. 

### Fix summary

Due to internal policy restricting permissions on that account (except when temporarily doing something that requires higher permissions), we needed to move the CLA Assistant setup to a different Github account that could remain an admin at all times.

### Steps to fix

1. Set current account temporarily back to admin
2. From CLA Assistant UI, select unlink
3. Manually remove the webhook in the Github UI (unlink did not remove it)
5. Switch to the new (admin) account and link the ORIGINAL gist to the CLA Assistant
6. Maybe it wasn't needed, but we used the Recheck PR's button to make sure everything was up to date
