### ISSUE TITLE
CLA-Assistant integration not working

### ISSUE THREAD

**Issue by ThorstenBux** [cla-assistant/cla-assistant#122]
Hello all,

I tried to integrate CLA assistant into several projects but somehow it does not accept the CLA signing. 

You can have a look here:
https://github.com/ThorstenBux/Testing
Change a file and open a pull request. For me it always shows CLA not signed even though I signed it. 
You can see this here:
https://github.com/ThorstenBux/Testing/pull/5

Thanks for your support
Thorsten

**Comment by KharitonOff** [comment]
Hi Thorsten,

thank you very much for opening this issue. I found the cause: it seems that since 11th of June Github started to use a special account for commits, which are done via github web interface: https://github.com/web-flow
As CLA assistant checks the list of PR-committers it founds a committer who hasn't singed your CLA and it's web-flow 😄 

I'll let you know as soon we'll fix it.

**Comment by KharitonOff** [comment]
Now the fix is productive. Could you check it, please?

**Comment by ThorstenBux** [comment]
Hi thanks for your very fast reaction.

If I create new PRs it works like a charm. However the previously created PR still show that the CLA is not signed.
I even tried the option "Recheck PRs" on the cla-assistant.io website. But no difference.

**Comment by KharitonOff** [comment]
now it seems to work, does it?

**Comment by ThorstenBux** [comment]
Awesome, yes all works well now. Thanks a lot
