### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by 0xbaadf00d** [cla-assistant/cla-assistant#147]
Your CLA system don't work.

I have contributed to GOGS project (here PR link)
https://github.com/gogits/gogs/pull/3371

But CLA system don't aware i have already validated CLA on your website :
https://cloud.githubusercontent.com/assets/1005086/17516052/76382388-5e3c-11e6-967d-2fff159564eb.png

**Comment by KharitonOff** [comment]
So far everything is ok. CLA assistant checks all committers and the first commit was done with another e-mail. 
![bildschirmfoto 2016-08-09 um 14 42 57](https://cloud.githubusercontent.com/assets/8480657/17516610/c2096044-5e3f-11e6-856d-af7068bbb269.png)
As mentioned in CLA assistant's comment you can add this address to your github account to let Github identify you as the committer of this commit

**Comment by 0xbaadf00d** [comment]
I can't add "None" as email address on github. I you check last commit, you will see that the email address is OK and if you check Github username and commit author, you will see is the same (0xBAADF00D == 0xbaadf00d)

**Comment by KharitonOff** [comment]
Ok, I see. The problem is, CLA assistant relies completely on GitHub-Api and as long GitHub can't identify you as a committer of the first commit CLA assistant can't do it either 😞 
Maybe this link can help you: https://help.github.com/articles/changing-author-info/  
another way I could imagine is to create a new PR with recommitted/squashed changes, see http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
