### ISSUE TITLE
CLAassistant thinks CLA isn't signed, yet it is

### ISSUE THREAD

**Issue by mmoayyed** [cla-assistant/cla-assistant#185]
![image](https://cloud.githubusercontent.com/assets/1205228/21104800/26028190-c045-11e6-9658-70fc81b80fb3.png)

Issue:
https://github.com/apereo/cas/pull/2193

The CLA contributors list shows that DavidRG13 has indeed signed the CLA. What is the reference to "David Rodriguez" ?

**Comment by mmoayyed** [comment]
cc @DavidRG13

**Comment by KharitonOff** [comment]
"David Rodriguez" is the name of the committer. Probably @DavidRG13 is "David Rodriguez" but the e-mail address used in this commit was not added to @DavidRG13's profile. That's why GitHub doesn't recognize the committer (this is explained also in CLA assistant's comment and there is a link to GitHub Wiki).
