### ISSUE TITLE
Delay updating GitHub after signing CLA

### ISSUE THREAD

**Issue by SendGridDX** [cla-assistant/cla-assistant#206]
When someone signs the CLA, in some cases the PR is updated right away, in other cases there can be a delay for several minutes. 

Any guidance on where I should focus my debugging would be appreciated. Thanks!

**Comment by KharitonOff** [comment]
@SendGridDX since GitHub API doesn't respond reliably strait after creating a PR, we enforce CLA assistant to wait a minute before trying to update the PR status. You can find this setting in config.js (see server.github.enforceDelay) You can overwrite it by setting env. parameter "GITHUB_DELAY" to any other value 
The implementation of this delay is in src/server/webhooks/pull_request.js
