### ISSUE TITLE
Questions about the way of handling webhook event

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#244]
Since I'm making some changes,  I'm confused by the code which handles webhook event. For me, [cla.check()](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/services/cla.js#L108) is able to handle a webhook event. The function [handleWebhook()](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/webhooks/pull_request.js#L15) first get commits(**but don't use the commits**) and then call cla.check(). I feel it's really redundant. Could anyone give me some guidance?

**Comment by thojansen** [comment]
@KharitonOff would be the right one to help out here 😃

**Comment by KharitonOff** [comment]
The main reason of getting commits first and calling cla.check() afterwards is the problem with GitHub API we faced lately: sometimes the PR API (https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request) didn't respond with appropriate data straight after the PR was created, it took a bit of time until the API responded as expected. 

So, in order to handle this latency I added this api-call before check() and the timeout function for the case the GitHub API response has no data yet.
