### ISSUE TITLE
CLA status reporting not working 

### ISSUE THREAD

**Issue by c0ze** [cla-assistant/cla-assistant#256]
first this https://github.com/iron-io/functions/pull/637
then this https://github.com/iron-io/functions/pull/640
looks similar to #77

**Comment by c0ze** [comment]
@KharitonOff can you please have a look into this ?

**Comment by LexManos** [comment]
Seems to be happening to me as well. Last PR CLA-Assistant was active on was 7 days ago [here](https://github.com/MinecraftForge/MinecraftForge/pull/4312#issuecomment-323029342). Worth noting that that was just a comment, and that PR doesn't have a CLA check.
After that we've had a few PRs with no word from the bot. And clicking the 'Recheck PRs' button in the settings panel does nothing... 
Current PRs:https://github.com/MinecraftForge/MinecraftForge/pull/4339 https://github.com/MinecraftForge/MinecraftForge/pull/4336
It seems things started to break 17/18 days ago. As [this PR](https://github.com/MinecraftForge/MinecraftForge/pull/4284) has the CLA check but [this](https://github.com/MinecraftForge/MinecraftForge/pull/4286) doesn't.

**Comment by KharitonOff** [comment]
@c0ze Sorry for that and for the late response. I'm currently on vacation, that's why I could not react in time and I still have limited access to analyse the problem.
If your problem is related to the issue #77 (wrong access token), then you can just log in to cla-assistant.io and a new token will be stored for your repos.
If there are some problems with the webhook on github, you can either check it in github directly (repository settings -> webhooks) or just remove the link for your repo in cla-assistant.io and create it again (all signatures remain active as long the gist file keeps unchanged).

I have also noticed that the name of your CLA status is obsolete, see the #211 

@c0ze @LexManos As soon as I am back from vacation I'll check the logs and source code on my side.

**Comment by LexManos** [comment]
Hate to bump this, but I have no idea how long you're on vacation. But it's been 10 days. Any update on this?

**Comment by c0ze** [comment]
My problem has been solved after deleting the link and recreating again.
It seems my problem was about the #211 .
(Make sure to export your contributions before deleting your link if you're going about this route.)

**Comment by KharitonOff** [comment]
@LexManos CLA assistant has indeed wrong/outdated token stored for your repository. I've changed the token-update mechanism. The workaround from @c0ze would solve the issue in your case, but I hope you haven't tried it yet :) If not, it would be very helpful if you would logout and login into CLA assistant and trigger the "Recheck PRs" button.

**Comment by KharitonOff** [comment]
@c0ze glad to hear, that your problem is solved now! 👍  Sorry for the inconvenience!

**Comment by LexManos** [comment]
@KharitonOff Thanks for taking a look, I was out of town for PAX this weekend and didn't have time to check in on this.
However, Relogging and hitting recheck seems to of worked. I did not try the workaround. So that's good. 
Just a suggestion it would be cool to see some form of progress/feedback for the recheck button. As right now it just clicks and freezes the page for a second. But seems to of worked.
