### ISSUE TITLE
Document setup when using 2FA

### ISSUE THREAD

**Issue by ketan** [cla-assistant/cla-assistant#274]
I'm unable to setup CLA assistant because the user specified by `GITHUB_USER` is using 2FA. Could someone help out?

**Comment by ketan** [comment]
Any pointers would be appreciated. I can submit these code changes on a PR>

**Comment by KharitonOff** [comment]
@ketan sorry for long delay. I would start with the method `call` in github service (`src/server/services/github.js`) which accepts basicAuth credentials in order to call github api with basic authentication (see line 132). As POC you could change this block to something like 
```
        if (basicAuth) {
            github.authenticate({
                type: 'oauth',
                token: <YOUR GITHUB USER TOKEN>
            });
        }
```
If this works, then you can update all the places, where github service is called with `basicAuth` parameter, like 
`src/server/passports/github.js`
`src/server/passports/token.js`
`src/server/services/pullReuest.js`
`src/server/controller/count.js`
