### ISSUE TITLE
Could you help me understand why we need to drop all index of 'clas' collection and recreate again?

### ISSUE THREAD

**Issue by MichaelTsengLZ** [cla-assistant/cla-assistant#291]
The code snippets [here](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/documents/cla.js#L36) and [here](https://github.com/cla-assistant/cla-assistant/blob/master/src/server/documents/repo.js#L24) are a little bit confusing for me. Could you help me understand why we need to drop all index and recreate again? Why only 'repos' and 'clas' collections need to recreate index? Can I just keep the previous index as it is?

**Comment by KharitonOff** [comment]
Hi Michael,

I've updated the indexes as reaction to the bug reported by @splix in his comment on the issue #264 The problem was, that a repository can be deleted and newly created with the same name. If the deleted repo was already linked in CLA assistant, then we select and check not unique signatures and repositories without considering the repoId.
