### ISSUE TITLE
Experiencing 502 errors when signing CLA

### ISSUE THREAD

**Issue by rojotek** [cla-assistant/cla-assistant#340]
I'm currently testing CLA assistant on a personal repo before considering rolling it out across our organisation.

Unfortunately, people are getting 502 errors after signing the CLA.

They get the expected CLA not signed message, and then when they sign it they end up with a 502.
URL to the linked Repo/Org:
https://github.com/rojotek/swift-run

Steps to reproduce the problem:

1. Create a PR against the repo
2. Sign the CLA
3. get the 502.  It will initially look like the CLA wasn't signed to the signer, but really it was

What is the expected result?

Don't get the 502. PR check will pass.
What happens instead?
get the 502 error.  It will initially look like the CLA wasn't signed to the signer, but really it was

**Comment by KharitonOff** [comment]
Thank you very much for reporting this!! 👍

**Comment by rojotek** [comment]
So the cause for me was missing the json metadata with the gist license file.  It would be awesome if there was a check for metadata somewhere to help catch this.  Maybe in the validations when setting up the license.

**Comment by KharitonOff** [comment]
I'm glad that you could find the problem and solve it!
The 502 shouldn't happen and there was a bug in the last implementation. Normally you see an error message on the CLA page if JSON format is wrong. A metadata file is optional, that's why we don't validate it (it would be good to have the validation, but there is too little capacity on our side to implement it too).
