### ISSUE TITLE
Contributor has signed CLA but sill shows check as "pending" on pull request

### ISSUE THREAD

**Issue by decause** [cla-assistant/cla-assistant#352]
URL to the linked Repo/Org: https://github.com/twitter/chill/pull/314

Steps to reproduce the problem:

1. I double checked at our export list and can confirm that the user has signed the CLA, but the check is still "pending" on the pull request.

What is the expected result?
The check should pass, and the dot should be green.

What happens instead?
The check is pending, and the dot is yellow.

**Comment by decause** [comment]
It seems like the bot is looking for "Zanfeng Feng" and the entry in our export is fengzanfeng?

**Comment by KharitonOff** [comment]
@decause yes, this happens often. Some contributors doesn't use the same e-mail for their commits as they have stored in their GitHub account. That's why we placed the info in the comment from CLA Assistant

> Zanfeng Feng seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.


there is also a link to the GitHub documentation with proposal how to solve this https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by akki-jat** [comment]
I am facing the same problem. I have already added account from which I committed to my GitHub account.
Even though it is not reflecting.

**Comment by KharitonOff** [comment]
@akki-jat If you have already added the email you have used in the commit to your GitHub account, then the CLA Assistant needs to be triggered in order to recheck the PR. It can be done either via a PR webhook (just update the PR by adding a comment or a commit) or via a "Recheck PR" in the CLA Assistant ui (only the project owner can do it)

**Comment by akki-jat** [comment]
@KharitonOff I added both comment and commit after updating the email, but even thought it is showing pending.
And I can't confirm with "Recheck PR" option.

**Comment by KharitonOff** [comment]
@akki-jat can you provide me the url of the PR, please?

**Comment by akki-jat** [comment]
@KharitonOff here it is [https://github.com/webpack-contrib/style-loader/pull/333](https://github.com/webpack-contrib/style-loader/pull/333)

**Comment by KharitonOff** [comment]
@akki-jat I've reported your issue to GitHub and will let you know as soon they'll contact me. It is definitely not an issue with the CLA Assistant, we rely on the data, provided by GH. If GH can not recognise you as a committer, then CLA Assistant can't do it to either.

**Comment by akki-jat** [comment]
@KharitonOff ok, thanks.

**Comment by KharitonOff** [comment]
@akki-jat I've just forwarded you the response from GitHub via email

**Comment by akki-jat** [comment]
@KharitonOff thanks, issue is resolved.

**Comment by yanrongzhen** [comment]
https://github.com/alibaba/fastjson/pull/4185  this pr also have the same problems, always in pending status.

**Comment by KharitonOff** [comment]
@yanrongzhen your issue is resolved now, right? I see you have created a new PR, that has passed the check successfully.
