### ISSUE TITLE
[Doc] What repo rights does GITHUB_USER, as well as user configuring CLA need to have?

### ISSUE THREAD

**Issue by andrerom** [cla-assistant/cla-assistant#361]
Partly related to #320.

Would be good if doc was much more clear on what rights does:
- GITHUB_USER need?
- User logging in to administrate instance ("Configure CLA") need?

Context:
We have an issue where web hooks don't trigger CLA check, even if everything seems fine on Github side with 200 response from CLA assistant instance as seen on hook on Github side. However running "Re-check PRs" fixes it _(CLA check on PR's appears)_, so a bit unsure what is triggering this.
_(Tested on 1.8.1 and master)_

**Comment by robinmuilwijk** [comment]
Hi, we are still eager to solve the issue posted on August 3. Does anyone have a suggestion to our problem?

**Comment by KharitonOff** [comment]
@robinmuilwijk sorry for long delay, I've overseen the actual problem your are facing, I thought this issue was just requesting a detailed documentation.
GITHUB_USER doesn't need any special rights. This should be a github user with credentials, who will write/edit/delete comment on PRs (no special rights are needed for this activities on GitHub). 
Project owners (users who links a repo or an org on CLA assistant) need admin rights of the according Repo/Org. The user provides following rights/scope to the application: ```'user:email', 'public_repo', 'repo:status', 'read:repo_hook', 'write:repo_hook', 'read:org', 'gist'``` (here you can find the description of the scopes: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)
Can you name the repository you have tested? Is the issue reproducible?

**Comment by robinmuilwijk** [comment]
@KharitonOff thanks for the answer, I'll check with @andrerom if he can look at this.
