### ISSUE TITLE
How to handle user being removed from org?

### ISSUE THREAD

**Issue by waldyrious** [cla-assistant/cla-assistant#368]
We have been using cla-assistant for a while in [tldr-pages/tldr](https://github.com/tldr-pages/tldr). I was the one who set it up. However, in accordance to our governance processes, I was recently moved from an owner of the org to collaborator in the repo. This seems to have removed the configuration of cla-assistant from the tldr repo.

The checks (e.g. [here](https://github.com/tldr-pages/tldr/pull/2259)) are not returning any status, and I now see nothing in the "Linked Repositories" section after logging in to https://cla-assistant.io. The signing link (https://cla-assistant.io/tldr-pages/tldr) still appears to work, though. The gist hosting the agreement is [still up](https://gist.github.com/waldyrious/e50feec13683e565769fbd58ce503d4e) as well.

What should we to to restore the service without losing the list of current signatories?

/cc @agnivade, @sbrl, @pxgamer

**Comment by waldyrious** [comment]
This may be related to #366, but as I'm not sure, I opened a separate issue.

**Comment by sbrl** [comment]
Should we re-add you temporarily until this can be resolved, @waldyrious?

**Comment by sbrl** [comment]
Invitation sent!

**Comment by waldyrious** [comment]
Thanks, I've just accepted the invitation. Let's see if that works as a stop-gap solution until this issue is resolved.

One good thing that I can confirm is that logging in to cla-assistant.io I do see tldr-pages listed as a linked project, so things hopefully are connected again. So perhaps a solution to this issue is the ability to transfer such a connection to another accounts (or even better, associate them with organizations rather than individual accounts). Let's wait and see what the cla-assistant people say :)

**Comment by KharitonOff** [comment]
@waldyrious I'm sorry for a late response (due to vacation time it takes us a bit longer to handle the issues).
Actually cla-assistant should override your token (if it is not valid anymore) with a new one as soon as somebody, who has a valid permission signs in to it.
In future we would like to stop using personal tokens and use an app token instead.

**Comment by waldyrious** [comment]
I'm sorry @KharitonOff, I didn't really understand this:

> Actually cla-assistant should override your token (if it is not valid anymore) with a new one as soon as somebody, who has a valid permission signs in to it.

I meant to reply when I first read your reply but for some reason it slipped me. Could you clarify the steps we should take?

The situation is currently that I can't be removed as a member of the tldr-pages org because the cla-assistant integration is associated to my account. Are you saying it's possible for another member of tldr-pages (e.g. @sbrl) to take ownership of that integration, preserving the list of CLA signataries for the tldr repository?

**Comment by KharitonOff** [comment]
Yes. CLA assistant checks the stored tokens of the repos each time an admin signs in. Assuming your token has not enough rights anymore (because you have been moved from an owner of the org to collaborator in the repo) and @sbrl is an admin of the org. As soon @sbrl signs into CLA assistant, the tool checks all stored tokens for the repos @sbrl sees in the list and finds the repo with your (invalid) token and replaces the old token with the new one (from @sbrl).
All signatures are stored separately and don't have any dependency to the person who has linked the repo.

**Comment by waldyrious** [comment]
Ok, thanks, that clarifies things! We'll go ahead and do as you described. Can you do that, @sbrl?

**Comment by sbrl** [comment]
There - I've converted you to an outside collaborator, @waldyrious, and then signed into [cla-assistant.io](https://cla-assistant.io/). How can I verify that it can rechecked & applied the token update please, @KharitonOff?

**Comment by waldyrious** [comment]
Do you see the tldr project when you log in to cla-assistant.io? Clicking on it should give you access to the info about the tldr repo's cla-assistant integration, including the ability to view the list of signataries. Can you check if you see anything like that? As for confirming that it is still working, I suppose new PRs to the tldr repo should have the CLA check continue to work normally.

**Comment by KharitonOff** [comment]
@sbrl I can confirm that the token for the linked repo tldr-pages/tldr has changed

**Comment by sbrl** [comment]
Thanks, @KharitonOff :smiley_cat:
