### ISSUE TITLE
Access for other organization member

### ISSUE THREAD

**Issue by Pro** [cla-assistant/cla-assistant#374]
URL to the linked Repo/Org: https://github.com/open62541/open62541

In #99 you mention that every owner of a repository should see the registered repository when logging in to https://cla-assistant.io/

I registered our organization (open62541) with CLA Assistant and I can also see the linked repo:

![image](https://user-images.githubusercontent.com/251973/45297088-81fae400-b504-11e8-9e7d-b894e0c54a4f.png)

Another owner of the organization (@jpfr) does not see the repository if he logs in:

![image](https://user-images.githubusercontent.com/251973/45297127-a060df80-b504-11e8-91db-a28ffdb26566.png)

How can we make sure that all organization members have access to the CLA settings?

https://github.com/orgs/open62541/people

Is it related to the visibility setting of each member? I.e. I'm a public member, whereas @jpfr is a private member.

**Comment by Pro** [comment]
@jpfr is now also a public member of the organization, but the repo does still not show up when he logs in. Could it be that you need to trigger a manual resync of the repo?

**Comment by KharitonOff** [comment]
@Pro this is an issue of auth scope. You have linked not a repo but an org. In order to link an org or to see linked orgs user needs to extend the provided OAuth scope. @jpfr needs to click on "ConfigureCLA" and choose "want to link an org?"
![screen shot 2018-09-10 at 15 14 56](https://user-images.githubusercontent.com/8480657/45299690-a8248200-b50c-11e8-9191-e76b6af7888f.png)

**Comment by jpfr** [comment]
Great! I got it to work.
Thanks for the assistance.
