### ISSUE TITLE
cla-assistant lost most contributors

### ISSUE THREAD

**Issue by ktsaou** [cla-assistant/cla-assistant#376]
Hi,

A few days ago we installed cla-assistant for https://github.com/firehol/netdata
We imported our previous list of contributors that had signed it in the past and we integrated it with github to receive new ones.

Several people had signed the CLA since then. The total count I recall was 48 contributors.

I see now and it has only 6 contributors signed the CLA.

Any ideas what is happening?

**Comment by KharitonOff** [comment]
Hi,
I suppose it's because of change you have done on the linked gist file 2 days ago. CLA assistant handles each version of the gist file as a separate version of the agreement. As soon the agreement changes contributors need to sign it again. Unfortunately we do not have a semantic versioning mechanism yet, that means even if you do a minor formatting change CLA assistant treats it as a new content. As a workaround, you can use the export/import functionality. You can export the list of signees for each version of the CLA separately.

**Comment by ktsaou** [comment]
Oh I see. Thank you!
Since the change I made was to just mention cla-assistant, I understand I can export the contributors and import it to the current.
