### ISSUE TITLE
Garbled text (apparently a character encoding issue, apparently an apostrophe was intended)

### ISSUE THREAD

**Issue by basil-bourque** [cla-assistant/cla-assistant#395]
URL to the linked Repo/Org:
https://cla-assistant.io/vaadin/framework?pullRequest=11387

Steps to reproduce the problem:

1. Display the CLA document, prompting "Sign in with GitHub to agree".
2. Look in section # 6 for phrase “any third partyâ€™s copyrights” where apparently “any third party’s copyrights” was intended.

What is the expected result?

Apparently “any third party’s copyrights” was intended

What happens instead?

Phrase “any third partyâ€™s copyrights” appears with three unintended characters between `y` and `s`.

**Comment by michael-spengler** [comment]
Dear @basil-bourque . 

Thank you for reporting this.

The CLA assistant uses https://gist.github.com/ to store the individual CLAs. 
We just checked and saw that the "strange characters" come from the CLA stored in the gist file.

Recommendation: Contact the owners of the repo (https://github.com/vaadin/framework) and ask them whether they would like to correct their gist file and with this the content of their CLA. The downside of this would be that all the already granted signatures would be invalidated due to the change / the new version of the CLA.
