### ISSUE TITLE
Can a person see/filter a list of the people who have signed CLAs

### ISSUE THREAD

**Issue by chet-ensign** [cla-assistant/cla-assistant#401]
One of our needs is for staff or for a maintainer to be able to look at CLA records to see if a person has signed the CLA. For example, if one of our member companies contacts us and asks for a list of their employees who have signed CLAs. We have a home-grown CLA solution (I like yours better!) and I've attached a screen shot. 

Is something similar possible with CLA Assistant? 

![cla-list](https://user-images.githubusercontent.com/11619141/51054478-f3c66580-15aa-11e9-949c-1196b9909e69.png)

**Comment by KharitonOff** [comment]
Unfortunately there is no such feature in CLA Assistant yet.

You can review the whole list of contributors by clicking on the number of signers in the admin UI. You can sort the list by name in order to find the user easily. You can also export the the whole list with all metadata in a .csv format.
![screen shot 2019-01-14 at 14 47 19](https://user-images.githubusercontent.com/8480657/51166377-8f095480-18a3-11e9-9645-000effd2c13c.png)

**Comment by chet-ensign** [comment]
Thanks for the prompt answer. This gives me the info I needed. The key thing is that there are ways to retrieve the list.
