### ISSUE TITLE
CLA signing is case sensitive, but whitelisting is not

### ISSUE THREAD

**Issue by benwerd** [cla-assistant/cla-assistant#413]
URL to the linked Repo/Org: https://github.com/unlock-protocol/unlock/

Steps to reproduce the problem:

1. Push a PR with an all-lowercase version of your username
2. Sign CLA
3. Push another PR with a capitalized version of your username
4. CLA assistant treats this as a new user, says it hasn't signed
5. Import CSV into CLA assistant containing capitalized version of username to whitelist it

*What is the expected result?*

Ideally CLA assistant should not treat usernames as being case sensitive, and should have seen that the CLA was signed at point 4 above.

*What happens instead?*

CLA assistant does not whitelist the username, because it finds the all-lowercase version. Contributor has to re-sign the CLA.

**Comment by KharitonOff** [comment]
@benwerd thank you for letting us know! Unfortunately I don't understand the issue completely :( Do you have a sample PR where the username is in all caps? As far I know, GitHub enriches the metadata of commits with user infos depending on the email address you use. I've never heard about a possibility to change the username... if you mean the user.name in git config, CLA assistant doesn't take it into consideration at all.

**Comment by benwerd** [comment]
It's actually possible to change the username case when you commit via the command line - the underlying issue is with git, not with GitHub. It's probably a fairly edgy edge case, but it happened to us nonetheless!

See: https://github.com/unlock-protocol/unlock/pull/1419

We merged it anyway, but it was a startling thing to see.

**Comment by KharitonOff** [comment]
Unfortunately we can't do much about it. CLA assistant relies fully on the information provided by GitHub APIs. Since GitHub itself is unable to identify the committer and assign this commit to a GitHub user we can not check whether this user has signed the CLA or not. 
Here you can see that the committer of this commit is not identified. Gray octocat as avatar is the sign that GitHub could not assign the person to an existing GitHub user.
<img width="264" alt="screen shot 2019-02-13 at 11 10 11" src="https://user-images.githubusercontent.com/8480657/52704062-0a802380-2f80-11e9-9bd9-b87358f35123.png">
Usually it happens when the email address of a commit differs from the email address of the GitHub user. I'm guessing that @hardlydifficult hasn't store the email address she/he uses for commits in her/his GitHub account
