### ISSUE TITLE
Unable to sign CLA

### ISSUE THREAD

**Issue by SubhanAli94** [cla-assistant/cla-assistant#443]
URL to the linked Repo/Org:
https://github.com/android/plaid/pull/707#issuecomment-495941763

Steps to reproduce the problem:

1.I created a pull request but after creating a pull request I received a message from bot to sign cla. I signed it and wrote 'I signed it!' multiple times with different accounts but it isn't allowing me to pass that.

What is the expected result?
cla:yes should e visible in my PR status.

What happens instead?
cal:no is coming continuously.

**Comment by KharitonOff** [comment]
Though google doesn't use CLA assistant for checking the CLA signatures I believe to be able to help you here... :)
It seems, that your agreement is accepted by @googlebot, however there are 3 last commits, which cannot be assigned to any github user (see the grey octocat icon instead of your user icon near the commit message). This happens when the email address, you have used for the commit (see your git settings), is not assigned to any github account.

To solve this issue you should add your email address ('subhanali.softengg@gmail.com ') to your github account, then GitHub will automatically assign this commit to you and your agreement becomes valid also for these 3 commits.

**Comment by SubhanAli94** [comment]
Hi KharitonOff, my this email id is already associated with GitHub account. Its my default email id.

**Comment by KharitonOff** [comment]
I see. But the Problem seems to be with GitHub not the @googlebot because your commit is still not assigned to your account (maybe you have a typo in your email adress either in commit or in your account). For more information about it visit https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user
