### ISSUE TITLE
CLA check never reports on PRs

### ISSUE THREAD

**Issue by mtreinish** [cla-assistant/cla-assistant#446]
URL to the linked Repo/Org: https://github.com/Qiskit/qiskit-ignis

Steps to reproduce the problem: 

1. Open a new PR and/or push an update to an existing PR

What is the expected result?

The CLA assistant bot will comment on whether all commit authors have signed the CLA or not.

What happens instead? 

The bot never responds and because it's a required check on the repo it's stuck waiting. For example see:

https://github.com/Qiskit/qiskit-ignis/pull/218 (or any currently open PR)

This is only effecting this repo in the Qiskit github organization, other repositories seem to be getting prompt responses from the bot.

**Comment by mtreinish** [comment]
It started returning again

**Comment by mtreinish** [comment]
Sorry to flip flop on this, but it's back to the same state, the open PRs have been sitting for hours without the bot returning.

**Comment by KharitonOff** [comment]
No problem. You seem have linked the whole organisation and the bot doesn't work properly for this repo... In our logs we see, that the user (his/her token) doesn't have enough rights for creating a status on PRs. I assume the user, who has linked the organisation doesn't have admin rights for this one repository. Can you confirm it?

**Comment by mtreinish** [comment]
Hmm, the organization link was done by @jaygambetta who definitely has admin rights on this repo. We also didn't change anything related to users or permission levels and it was working fine just a few days ago.

**Comment by KharitonOff** [comment]
ok... sometimes it can happen that if another user with org-membership right (but still limited right for some repos) signs into the admin view of CLA assistant the token of the linked org gets overwritten.
In order to fix it, I would suggest that the admin of your org goes to the CLA assistant and clicks on "Recheck PRs" for your organisation. This should solve the issue.

<img width="373" alt="Screen Shot 2019-03-13 at 17 52 40" src="https://user-images.githubusercontent.com/8480657/60187745-644a0180-982e-11e9-84fe-5c8b3a54b24d.png">

**Comment by KharitonOff** [comment]
I am sorry for the inconvenience :( We hope that in the near future we'll be able to switch from user tokens to the App Tokens using GitHubApp solution. Then there will be no confusion with rights and tokens any more.

**Comment by mtreinish** [comment]
Ok, it looks like doing that fixed it. Thanks for the help.
