### ISSUE TITLE
The width of repository name in 'Linked Repositories' is not wide enough to read.

### ISSUE THREAD

**Issue by jennifer-shehane** [cla-assistant/cla-assistant#452]
URL to the linked Repo/Org: https://github.com/cypress-io/cypress-example-kitchensink

Steps to reproduce the problem:

1. Have multiple linked repos within an organization domain.
2. Go to cla-assistant and look at 'Linked Repositories' list
3. I can't tell the repos apart with the current width of the 'repository' column. They are truncated with ellipsis, so I have to hover over each one and look at the link's url to figure out which repo it is.

<img width="492" alt="Screen Shot 2019-07-09 at 10 15 17 AM" src="https://user-images.githubusercontent.com/1271364/60858091-f7256b80-a232-11e9-804d-8b728e27acd3.png">
 

What is the expected result?

I just want to be able to scan the list without hovering to see which repo row I'm on.

Browser/version: Chrome 75, Mac

**Comment by ibakshay** [comment]
Hi @jennifer-shehane, I don't know if you already know this feature `org-wide CLA`of CLA Assistant or not. If you already know, then great 💯.
If not, this might be helpful to you. Instead of linking each and every repository of an organization, you can also configure Organization wide CLA. You can have a look at issue  https://github.com/cla-assistant/cla-assistant/issues/457# on how to configure `org-wide CLA`. 

**Note**:  However, the contributors need to sign again since they have signed the CLA only for the repository and not for the whole organization. However, If you are using the same content of the CLA, you can import the previous signatures.  This is also  a legal question, whether the agreement, signed for a repo can be imported and  valid for the whole organization (multiple repos)

**Comment by jennifer-shehane** [comment]
@ibakshay No, I didn't know ya'll had this, Thanks!

**Comment by jennifer-shehane** [comment]
Thanks for being so responsive. The new design is so helpful for us. 👍
