### ISSUE TITLE
user deleted in github still in the list for open pull request

### ISSUE THREAD

**Issue by obar1** [cla-assistant/cla-assistant#454]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. create a user
2. sign off a cla
3. drop the user and go back to the cla

What is the expected result?
ou get stucked
What happens instead?
you cannot go ahead as the user does not exist and cla cannot be signed anymore

**Comment by KharitonOff** [comment]
Can you provide the link to the PR where this issue appeared, please?

**Comment by obar1** [comment]
@KharitonOff  sure
https://github.com/delta-io/delta/pull/84

**Comment by ibakshay** [comment]
Hi @obar1, Is `Databricks CLA Assistant` is a  self-hosted CLA Assistant of yours?




<img width="797" alt="Screen Shot 2019-07-12 at 10 08 49" src="https://user-images.githubusercontent.com/33329946/61113495-b590fc80-a48e-11e9-9900-4c6e0fadee0c.png">

**Comment by obar1** [comment]
it s from datadricks

**Comment by KharitonOff** [comment]
I believe the solution for your problem would be to add the email address used for commits from Mario_Amatucci to a (your) GitHub account. Since the user was removed GitHub can not recognize the committer.
In general CLA assistant checks whether all committers (not the author of the PR) have signed the CLA.
