### ISSUE TITLE
Org and repos aren't appearing in my manage list

### ISSUE THREAD

**Issue by directionless** [cla-assistant/cla-assistant#459]
Hi. I'm an owner of [kolide](https://github.com/kolide), and I'm trying to understand how cla-assistant was configured. I know it was configured by a former employee, but not much else.

When I visit https://cla-assistant.io/ I do not see the expected linked repositories or orgs. I expect to either see the org listed (there is a org webhook) or I expect to see links to both [kolide/launcher](https://github.com/kolide/launcher) and [kolide/fleet](https://github.com/kolide/fleet)

It gets a bit thornier. When trying to debug, we added a new link to [kolide/fleet](https://github.com/kolide/fleet). So now I can see that, but that seems to have cleared the list of signed contributors.

cc: @terracatta, @zwass

**Comment by ibakshay** [comment]
Hi @directionless, The contributors have to sign again if the `gist URL` or `gist version` is changed. 
It can be the case where your contributors have signed in this format `https://gist.github.com/<gist owner>/<gist id>` but you have linked the gist in this format `https://gist.github.com/<gist id>`. Because if you select the gist from the drop-down when configuring CLA then the gist will be in this format `https://gist.github.com/<gist id>`.  The CLA Assistant will treat as two different gists and expects the contributors to sign again. 
Now you  can check If you are able to retrieve the contributors already signed by manually pasting the URL in this format `https://gist.github.com/<gist owner>/<gist id>` for https://github.com/kolide/fleet . 
**Steps**
1. On the repo row, click ***...*** and select **Edit**. 
![image](https://user-images.githubusercontent.com/33329946/61333975-f4c1a380-a828-11e9-9a12-243026e6a9d9.png)
2. click the **X** beside the **Select from Gist dropdown** 
![image](https://user-images.githubusercontent.com/33329946/61334080-4e29d280-a829-11e9-88ac-f9361876748c.png)
3. Now Paste in the gist url with the `https://gist.github.com/<gist owner>/<gist id>` format within **Paste a URL from a Gist** and click **Save**

**Comment by directionless** [comment]
Thank you for the suggestion. I just tried updating that to the form `https://gist.github.com/<gist owner>/<gist id>`, but upon save it reformats to `https://gist.github.com/<gist id>` and does not give me access to the old owners.

I still don't see any access for the other repositories cla-assistant is configured with

**Comment by ibakshay** [comment]
@directionless  So, you have pasted the gist URL `https://gist.github.com/<gist owner>/<gist id>` and then clicked **save**, but still you are not able to retrieve the old signatures ?.  Can you try once again because in most of the cases this will solve the problem :). 
![image](https://user-images.githubusercontent.com/33329946/61387369-4b28f380-a8b6-11e9-83b6-f60ebd0597ee.png)
The gist URL will reformat to  `https://gist.github.com/<gist id>` format even if you linked the item(repository or org) in this format `https://gist.github.com/<gist owner>/<gist id>`.

**Comment by ibakshay** [comment]
To be able to link the whole organization you need to provide additional auth-scope. Then you can link the whole organization. 
**Steps:**
1. click on **Configure CLA**
2. Then select **want to link an org** as below 
![image](https://user-images.githubusercontent.com/33329946/61389742-b7f1bd00-a8b9-11e9-86aa-ad8d79a5138e.png)

After you provide this extra auth scope, you will be able to link the whole organization.

**Comment by directionless** [comment]
@ibakshay I tried it several times, but sure. Once more with screenshots:

<img width="999" alt="Screen Shot 2019-07-18 at 00 24 33" src="https://user-images.githubusercontent.com/179542/61439150-d37ab900-a8f5-11e9-92c0-5af5b28a64fd.png">
<img width="999" alt="Screen Shot 2019-07-18 at 00 24 45" src="https://user-images.githubusercontent.com/179542/61439151-d37ab900-a8f5-11e9-8efe-768c6140ea10.png">
<img width="999" alt="Screen Shot 2019-07-18 at 00 24 55" src="https://user-images.githubusercontent.com/179542/61439152-d37ab900-a8f5-11e9-923d-265cd3d9cdf7.png">
<img width="999" alt="Screen Shot 2019-07-18 at 00 25 05" src="https://user-images.githubusercontent.com/179542/61439153-d37ab900-a8f5-11e9-8071-77d2f4aceb57.png">

**cla-assistant** is already configured for the kolide organization, and for kolide/launcher. So why can't I see that?

**Comment by ibakshay** [comment]
@directionless thank you for the details. You are not able to see the `kolide` organization even though it has already linked because you need to provide further 'auth-scope' in order to link the whole organization.
![image](https://user-images.githubusercontent.com/33329946/61453334-1a9c9480-a95e-11e9-8da8-445de78d0e47.png)

 After you accept this extra 'auth-scope', you can see the 'kolide' organization and also hopefully you can retain all the previous signatures. 
You can see my previous comment for the steps to provide this extra `auth scope`. 
https://github.com/cla-assistant/cla-assistant/issues/459#issuecomment-512337855

**Comment by directionless** [comment]
@ibakshay Ah. What you wrote was:

> To be able to link the whole organization you need to provide additional auth-scope

Which I did not interpret as meaning it needed that permission to see _existing_ links. But, having granted those permissions, I can now see the existing links. 

Which also helps resolve the kolide/fleet issue -- When it's configured for the individual repository it overrides and maintains a separate list than when it's configured for the org as a whole.

So I guess it's working as expected, and I can see what I need
