### ISSUE TITLE
Service timeouts causing a no CLA on a PR?

### ISSUE THREAD

**Issue by directionless** [cla-assistant/cla-assistant#465]
Hi! We have cla-assistant configured for the kolide organization. It does not appear inside https://github.com/kolide/launcher/pull/502 or https://github.com/kolide/fleet/pulls

The github webhook delivery log shows Service Timeout errors for the opened and synchronized events. Though it shows for success for other ones.

Do you know what's going on?

**Comment by KharitonOff** [comment]
Both PRs are looking good. I believe you are expecting CLA assistant to comment on this PRs. CLA assistant doesn’t comment PRs from contributors who have already signed the CLA by design. We don’t want produce to much noise. Only if there is a “new” committer CLA assistant will create a comment asking for accepting the CLA and of course update the comment as soon all committees sign it.

**Comment by directionless** [comment]
I had expected it to post something as a completed check, but didn't see anything last night.

I do see them this morning, and having not taken a screen shot, I don't know if it this is a my error in reading it, or if there was a delay.

The service timeout, however, I have in github's webhook logs

**Comment by directionless** [comment]
Seems unlikely that this will be debugged any further.
