### ISSUE TITLE
Unable to add/link a new organisation 

### ISSUE THREAD

**Issue by maheshika** [cla-assistant/cla-assistant#466]
URL to the linked Repo/Org: https://github.com/wso2

Steps to reproduce the problem:

1. Click on Configure CLA
2. Click on dropdown 

What is the expected result : organizations which are not linked should be listed in the drop down.

What happens instead : Non of the new organizations are listed

**Comment by ibakshay** [comment]
Hi @maheshika, Organizations is not showing up in the drop-down because you need to grant further 'auth-scope' permission for linking organizations. 
I already explained the steps on how to grant this permission for CLA Assistant in accessing your organization here https://github.com/cla-assistant/cla-assistant/issues/459#issuecomment-512337855 . 
If something is not clear, then feel free to reach out to us again :).

**Comment by KharitonOff** [comment]
If you aren’t able to link just **new** organisations, then you probably need to request an approval for CLA assistant in GitHub to access the new orgs (to do so, please follow the steps described here https://help.github.com/en/articles/requesting-organization-approval-for-oauth-apps )

**Comment by maheshika** [comment]
Hi Both, Went through the given steps and was able to add the other organizations. Thank you very much.
