### ISSUE TITLE
Signed CLA, not showing as signed

### ISSUE THREAD

**Issue by theblindprogramm3r** [cla-assistant/cla-assistant#468]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1. Reivew : https://github.com/KhronosGroup/OpenXR-SDK-Source/pull/108
2.
3.

What is the expected result?
- Shows CLA signed

What happens instead?
- Shows CLA not signed

**Comment by ibakshay** [comment]
Hi @theblindprogramm3r, I can now see that CLA is signed in this pull request   KhronosGroup/OpenXR-SDK-Source#108. So, CLA Assistant took some time to change the comment and status of this PR?

**Comment by Khronoswebmaster** [comment]
We are seeing more issues with CLA Assistant taking many hours to update the comment and status of PRs. When we try to login to CLA Assistant, we end up with a spinning Link in a grey circle forever. Is CLA Assistant experience technical difficulties? 

This PR is also not updating after 18 hours:
https://github.com/KhronosGroup/OpenCL-Headers/pull/53

**Comment by Khronoswebmaster** [comment]
Currently (August 7, 2019 11:53AM ET) seeing  timeouts when attempting to load cla-assistant.io:

              <span class="cf-error-type">Error</span>
              <span class="cf-error-code">524</span>
              <small class="heading-ray-id">Ray ID: 502a6645ee1eca5b &bull; 2019-08-07 15:50:55 UTC</small>
            </h1>
            <h2 class="cf-subheadline">A timeout occurred</h2>

On this URL:

angular.js:12996 POST https://cla-assistant.io/api/github/call 524

**Comment by ibakshay** [comment]
Hi @Khronoswebmaster, Yes we are facing some technical issues time and time again and we are trying to fix it. Now, https://cla-assistant.io should be loading properly. 

However, I have reviewed your Pull request KhronosGroup/OpenCL-Headers#53 and I don't think this  Pull Request is affected because of the technical issue. The comment is not updating because @kcencele has committed in this pull request from this other GitHub account @DziubanMaciejIntel  (he/she has mentioned in the comment). 
<img width="830" alt="Screen Shot 2019-08-07 at 18 48 12" src="https://user-images.githubusercontent.com/33329946/62641775-a9407800-b944-11e9-9758-88c8989ad0b6.png">

I believe @kcencele has not signed the CLA from this Github account @DziubanMaciejIntel instead signed the CLA  from @kcencele. 

If the committer @DziubanMaciejIntel in this Pull request has signed the CLA, then I am pretty sure that the Status and comment will be changed :) .

**Comment by Khronoswebmaster** [comment]
@ibakshay ... right you are :-)
