### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by KharitonOff** [cla-assistant/cla-assistant#47]
provide answers to following questions in README: 
https://github.com/eslint/eslint/issues/2503

**Comment by KharitonOff** [comment]
@thojansen @yaseminc what do you think about this? Do we need more points or should we add further points as soon further questions will arrive? 

## FAQ
### Where is the list of signees stored?
We store all the data in a MongoDB hosted by mongolab.com. As soon SAP gets its own cloud foundry platform ready for external usage we will probably move to this one.

### Is there a way to import/export the signee data?
You can see the list of signees on the user interface and there is also a possibility for you to export the list in the .csv format.

### If there's a problem, who can I contact for help?
In case of problems or for any further questions and requests you can just open an issue in GitHub or work with us together on the project.

**Comment by yaseminc** [comment]
**Please find my suggestions in **bold** ;) **

Where is the list of signees stored?

We store all the data in a MongoDB hosted by mongolab.com. (Not sure if we need this, because it is an unsure info and not necessarily interesting for the user. if it ever happens, we can share the info ;) "As soon **as** SAP gets its own cloud foundry platform ready for external usage, we will probably move to this one.")

**Where can I see the list of signees? Is there a way to import/export the signee data?**

You can see the list of signees on the user interface**. There** is also a possibility for you to export the list **as a .csv file.**

**Who can I contact for help?**

**In case of problems or any further questions, please open an issue in GitHub. We always appreciate helpful tips and support for the project.**

**Comment by thojansen** [comment]
Saying that we *probably* move somewhere is not really that helpful. I would skip that part. Everything else I think is fine and then we can expand this as soon as questions come in.

**Comment by KharitonOff** [comment]
:+1: @yaseminc @thojansen 
thank you
