### ISSUE TITLE
Getting "Contributor License Agreement is not signed yet." on pull request

### ISSUE THREAD

**Issue by GeoDerp** [cla-assistant/cla-assistant#480]
### Issue
Getting ```Contributor License Agreement is not signed yet.``` although it already has been. 
other commits (almost exactly the same) have passed without a problem but these two seem to be stuck.  

### URL to the linked Repo/Org:

[bitfocus/companion/802](https://github.com/bitfocus/companion/pull/802)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commit: 16172199a17107aa3f8b994bca4793bde9f0a978
[bitfocus/companion/801](https://github.com/bitfocus/companion/pull/801)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;commit: 8b3167fd0e294528606d75d2a22f46c05062c123

### Steps to reproduce the problem:

1. commit to an already existing pull request 

### What is the expected result?

```Contributor License Agreement is signed.```

### What happens instead?

```contributor License Agreement is not signed yet. ```

## Other Issues:
Page crash: ![image](https://paste.opensuse.org/view/raw/17c320be) - crash was on Firebox and chrome, but only once so far.
[error log](https://paste.opensuse.org/de01ae84)

**Comment by ibakshay** [comment]
Hi @GeoDerp,  I can now see that CLA is signed for both the Pull Requests [801](https://github.com/bitfocus/companion/pull/801) [802](https://github.com/bitfocus/companion/pull/802). The CLA Assistant has commented `CLA not signed` because you didn't add the Email address you used for those 2  commits to your  GItHub Account. After you added the Email address, the CLA Assistant recognised you as a valid committer and commented `CLA Signed`. For more details see [here](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user)

![Screen Shot 2019-09-02 at 10 59 12](https://user-images.githubusercontent.com/33329946/64103142-d03a7000-cd71-11e9-9fcb-d2093a4f925c.png)

**Comment by GeoDerp** [comment]
im not even sure where Geo comes from. All the commits are under GeoDerp and have my associated email address. https://github.com/bitfocus/companion/commit/16172199a17107aa3f8b994bca4793bde9f0a978.patch (my primary email is : 18461782+GeoDerp@users.noreply.github.com)

In saying that Geo does show up when I commit via command line: with the email geo@localhost.localdomain (git default email (only found that out yesterday)), but none of the commits seem to be coming from geo. Only GeoDerp, with the GeoDerp email.:confounded:

**Comment by GeoDerp** [comment]
Worse case scenario I can completely delete the pull requests and start again. This time making sure ```git config --global user.email``` is definitely set up properly.

**Comment by ibakshay** [comment]
> Worse case scenario I can completely delete the pull requests and start again. This time making sure `git config --global user.email` is definitely set up properly.

@GeoDerp If you have the patience to do so 😉

**Comment by GeoDerp** [comment]
Yeah, Ill just do that
