### ISSUE TITLE
when I tried to check in code it asked me to sign both pzou1974 and pzou

### ISSUE THREAD

**Issue by pzou1974** [cla-assistant/cla-assistant#486]
URL to the linked Repo/Org:
https://github.com/keikoproj/addon-manager/pull/14

Steps to reproduce the problem:

1.  go to https://github.com/keikoproj/addon-manager/pull/14
2.  I used user pzou1974 and it is signed but I still got blocked.
3.  not sure why pzou is related to pzou1974

What is the expected result?

What happens instead?

**Comment by ibakshay** [comment]
Hi @pzou1974, I just reviewed the pull request and it looks like there are commits like `test checkin` from **pzou** account as well. And the commits from this account **pzou** are not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) you used for the commit in your local git configuration. 

![Screen Shot 2019-09-16 at 09 17 36](https://user-images.githubusercontent.com/33329946/64940461-553e8280-d864-11e9-856b-ce63ba2b61d3.png)
