### ISSUE TITLE
CLA fails to load

### ISSUE THREAD

**Issue by kristinaspring** [cla-assistant/cla-assistant#492]
URL to the linked Repo/Org:
https://github.com/xmidt-org
https://github.com/xmidt-org/docs/pull/22

Steps to reproduce the problem:

1. Create a pull request
2. Open the link provided to try to sign the CLA

What is the expected result?
User should see the CLA and be able to sign it

What happens instead?
User sees a mostly blank page that says `Version:` and then a blank area

![](https://user-images.githubusercontent.com/56047579/66061593-c55c3200-e50d-11e9-8ff1-4c7e3fb628e4.png)

The screenshot is what the creator of the PR saw, but I could recreate the issue using Safari 13.0.1.

**Comment by ibakshay** [comment]
hi @kristinaspring, I'm sorry for the inconvenience. We have seen some performance outrage for the past 2 days or so. The CLA Assistant should be working fine. I have done the potential fix and please let me know if you are still facing the issue.

And I also checked that your [CLA](https://cla-assistant.io/xmidt-org/docs?pullRequest=22) works fine now.

**Comment by carlism** [comment]
It's still super slow!  The page is just blank for ages.  Our contributors complaining or confused thinking it's just broken since there's no indication the content is coming.

**Comment by ibakshay** [comment]
Hi @carlism , I am sorry for the inconvenience. We are yet to find the root cause for this performance issue and we are working on it. We will do some infrastructure refactoring and hopefully that will fix this issue. 

However, When I reviewed your PR, and I come to know that, there is also another issue which is blocking the PR. 
It looks like this commit **Added loader while fetching data** from  @coderwassananmol  is not recognised by GitHub because [he needs to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which he used for this commit in his local git configuration.

![Screen Shot 2019-10-08 at 16 00 53](https://user-images.githubusercontent.com/33329946/66402425-1c1dac00-e9e5-11e9-9ce6-c6b4d862c0d6.png)

**Comment by carlism** [comment]
@ibakshay Thanks!  I look forward to seeing the refactor results.  Also, I've referred the user to your comments.  Hopefully they can work the issue out.

**Comment by ibakshay** [comment]
@carlism , We have done the infrastructure refactoring and this issue should be solved by now :) .

**Comment by medvednikov** [comment]
Hi,

It takes 5 seconds to load for me on a modern CPU/100 mbit Internet.

It's just text and a button, maybe you could avoid using Angular for this page? It's very important for it to load fast.
