### ISSUE TITLE
CLA assistant down

### ISSUE THREAD

**Issue by jennifer-shehane** [cla-assistant/cla-assistant#493]
URL to the linked Repo/Org:

https://cla-assistant.io/cypress-io/cypress-documentation

Steps to reproduce the problem:

1. Go to https://cla-assistant.io/
2. Site never loads / partially loads / extremely slow
3. Can't log in to the site through GitHub

Our deployments depend on people being able to sign our CLA, so this is blocking our PRs.

## Optional

Browser/version: Chrome 77

**Comment by jennifer-shehane** [comment]
Now getting 502 errors

<img width="1002" alt="Screen Shot 2019-10-04 at 12 02 54 PM" src="https://user-images.githubusercontent.com/1271364/66222373-00da3600-e69f-11e9-8588-4bec8d382611.png">

**Comment by ibakshay** [comment]
Hi @jennifer-shehane, I am really sorry, we have seen some performance outrages for the past 2 days, and hence  that's why [CLA-Assistant](https://cla-assistant.io/) was extremely slow. I have done the interim fix while I am still investigating the issue and  [CLA-Assistant](https://cla-assistant.io/) is loading properly now. 

However, When I reviewed your PR, and I come to know that, this performance issue is not blocking your [PR2131](https://github.com/cypress-io/cypress-documentation/pull/2131).  
 It looks like this commit **added keyboard shortcuts to docs**  from @mishabruml is not recognised by GitHub because [he needs to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which he used for this commit in his local git configuration.

<img width="790" alt="Screen Shot 2019-10-05 at 12 04 02" src="https://user-images.githubusercontent.com/33329946/66253480-364b5600-e769-11e9-8345-69a80216209e.png">

**Comment by mishabruml** [comment]
I've added the email address used for the commit to my github account as a secondary email and gone through the CLA site "sign in with github", am redirected to the PR page, but the CLA status check still says "not yet signed" ?

**Comment by jennifer-shehane** [comment]
@ibakshay Thanks! Yah, combination of 2 issues that confused the source. We are aware of the email address discrepancies and inform our users when we find them not matching, but the fact it was 502'ing definitely redirected my focus. 

Thanks for the quick response. Will close since the site is back up.

**Comment by ibakshay** [comment]
Hi @jennifer-shehane, Yes!! you are right.. We are aware too that the users are facing cloudfare error 502 at times. Thank you for reporting 😄 .
