### ISSUE TITLE
Signing form is checked on the client

### ISSUE THREAD

**Issue by jeliebig** [cla-assistant/cla-assistant#494]
As a 17 year old the website doesn't allow me to sign CLAs I guess that is how it should work. But I figured that the form is checked on the client and not on the server. So I was able to sign a CLA by removing the disabled style from the button and submitting the form.

Steps to reproduce the problem:

1. visit any cla-assistant.io cla and fill out the form make sure you are not able to submit the form
2. open dev-tools in your browser and locate the button
3. remove the disabled style and press enter - now you can sign the CLA

What is the expected result?
I should not be able to submit my form or sign the CLA because I'm 17 years old.

What happens instead?
I remove the disabled style and are allowed to sign the CLA without changing my age.

I don't know anything about this project, so I am not too sure if this is an issue or just something that happens. From my understanding a check on a client should never happen and I believe there could be more stuff done by knowing that. This could also be a security issue I think.

**Comment by KharitonOff** [comment]
Thank you very much for the detailed description! We appreciate it very much.
We are aware of the possibility to manipulate the data. The point is, that the fields, where you enter the data are kind of custom fields, which can not be validated on the backend, since they defer from project to project and some of the open source projects do not use them at all. The only mandatory data for our application is the github identity of the signee. On user request we have provided the possibility to create custom fields for collection some additional data. Unfortunately as many open source projects we do not have much capacity to provide a very comprehensive solution and we are more than glad to get support from our community on improving the solution. You are very welcome to contribute on this topic if you wish 😄 
Thanks again for letting us know!
