### ISSUE TITLE
I have singed the CLA and still it is showing CLA not signed

### ISSUE THREAD

**Issue by ystanwar** [cla-assistant/cla-assistant#495]
URL to the linked Repo/Org: I have raised a [PR](https://github.com/Bahmni/openmrs-module-appointment-frontend/pull/10) to a repo and after signing the CLA also it is showing CLA not signed

Steps to reproduce the problem:

1.When I see the PR it says CLA not signed
2.When I go to sign it, it says CLA already signed

**Comment by ibakshay** [comment]
Hi @ystanwar, Thank you for reaching out to us. 
 I reviewed your [Pull request](https://github.com/Bahmni/openmrs-module-appointment-frontend/pull/10), and It looks like this commit **"Create a tabular structure to display data and some actions .."**  is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which you  used for this commit in your local git configuration.

![Screen Shot 2019-10-15 at 09 12 46](https://user-images.githubusercontent.com/33329946/66809100-fb95aa80-ef2c-11e9-9da0-163fbcbf2f18.png)

**Comment by ystanwar** [comment]
> Hi @ystanwar, Thank you for reaching out to us.
> I reviewed your [Pull request](https://github.com/Bahmni/openmrs-module-appointment-frontend/pull/10), and It looks like this commit **"Create a tabular structure to display data and some actions .."** is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which you used for this commit in your local git configuration.
> 
> ![Screen Shot 2019-10-15 at 09 12 46](https://user-images.githubusercontent.com/33329946/66809100-fb95aa80-ef2c-11e9-9da0-163fbcbf2f18.png)

@ibakshay: My email is already added to my GitHub account and I am not getting any message beside my commit as to describe the problem.
