### ISSUE TITLE
Merge check fails to detect previously signed contributor; contributor cannot resign for another org?

### ISSUE THREAD

**Issue by decause** [cla-assistant/cla-assistant#511]
URL to the linked Repo/Org:
https://github.com/twitter/chill/pull/351#issuecomment-551249633

Steps to reproduce the problem:

0. User andrewsmartin has indicated they have previously agreed to our CLA.
1. When I check our cla-asistant.io exports, andrewsmartin's name is listed under the 'twitterdev' org, but not our primary 'twitter' org.
2. It seems like our previously signed contributors are now being allocated to the 'twitterdev' org, rather than our primary "twitter" org? I could be mistaken, but it seems like a migration issue?
3. I was also under the impression that if the CLA text is the same across mutlple orgs, that checking would also work across all orgs? I don't think that andrewsmartin was able to 'resign' the CLA for our primary org, because he already agreed for 'twitterdev'?

What is the expected result?
I would expect that CLA-assistant would see that andrewsmartin agreed to our CLA in another org, and since they are linked, they get the green checkmark and approval to merge.

What happens instead?
andrewsmartin has a red X by their name instead, and is indicated as not having agreed.

**Comment by KharitonOff** [comment]
@decause the problem is that the "twitterdev" uses different gist url than "twitter". The gist file is the same, but the url is different:
"https://gist.github.com/twitter-service/a1ad5818c024dc4265f8b60e6d043f26#file-twcla-112217-txt" vs "https://gist.github.com/twitter-service/a1ad5818c024dc4265f8b60e6d043f26"

The solution would be to change the gist url of "twitterdev" to "https://gist.github.com/twitter-service/a1ad5818c024dc4265f8b60e6d043f26". But this would mean that all contributors, who has signed the CLA for this org will need to sign it again (unsell they have also signed the CLA for the "twitter" org). To avoid it you can export the signatures first and import them after update again.
