### ISSUE TITLE
Zero signatures on repository with many signatures?

### ISSUE THREAD

**Issue by nijikokun** [cla-assistant/cla-assistant#517]
URL to the linked Repo/Org:

https://github.com/kong/kong

Steps to reproduce the problem:

1. Login to CLA Assistant
2. Zero contributors signed
3. Visit PRs obviously people have signed.

What is the expected result?

See actual number of signers, and a list of people who have signed.

What happens instead?

See zero signatures.

---

I have clicked on multiple versions, with no signatures on any.

**Comment by ibakshay** [comment]
Hi @nijikokun, The contributors have to sign again if the `gist URL` or `gist version` is changed. 
It can be the case where your contributors have signed in this format `https://gist.github.com/<gist owner>/<gist id>` but you have linked the gist in this format `https://gist.github.com/<gist id>`. Because if you select the gist from the drop-down when configuring CLA then the gist will be in this format `https://gist.github.com/<gist id>`. 
Now you  can check If you are able to retrieve the contributors already signed by manually pasting the Gist URL in this format `https://gist.github.com/<gist owner>/<gist id>` for https://github.com/kong/kong. 
**Steps**
1. On the repo row, click ***...*** and select **Edit**. 
![image](https://user-images.githubusercontent.com/33329946/61333975-f4c1a380-a828-11e9-9a12-243026e6a9d9.png)
2. click the **X** beside the **Select from Gist dropdown** 
![image](https://user-images.githubusercontent.com/33329946/61334080-4e29d280-a829-11e9-88ac-f9361876748c.png)
3. Now Paste in the gist url with the `https://gist.github.com/<gist owner>/<gist id>` format within **Paste a URL from a Gist** and click **Save**
