### ISSUE TITLE
I do have signed the CLA for SAP/olingo-jpa-processor-v4 Version: 2020-01-31

### ISSUE THREAD

**Issue by SeriousSoftware** [cla-assistant/cla-assistant#543]
URL to the linked Repo/Org:
https://github.com/SAP/olingo-jpa-processor-v4/pull/101

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by ibakshay** [comment]
Hi @SeriousSoftware , Thank you for reaching out to us. 
 It looks like this commit **"Incubation 00: Chore corrected error with Maven configuration and rem…"**  is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which you used for this commit in your local git configuration.

<img width="739" alt="Screenshot 2020-03-07 at 11 09 35" src="https://user-images.githubusercontent.com/33329946/76141465-d8e36a00-6064-11ea-8ad9-48f3d8056221.png">
