### ISSUE TITLE
I do have signed the CLA and have an email address added to my GitHub account

### ISSUE THREAD

**Issue by luchua-bc** [cla-assistant/cla-assistant#548]
URL to the linked Repo/Org:
https://github.com/Semmle/ql/pull/3090

Steps to reproduce the problem:
I tried to submit a pull request to https://github.com/Semmle/ql but got the error showing "beichent seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account."

1. I did accept the CLA as shown in the screenshot below:
<img width="1043" alt="cla_signed" src="https://user-images.githubusercontent.com/37377780/77109439-4941a200-69fa-11ea-8ac3-7c2bc72fc8c5.png">

2. I still got the warning below even after clicking "recheck"
<img width="1103" alt="cla_warning" src="https://user-images.githubusercontent.com/37377780/77109625-9c1b5980-69fa-11ea-920f-4e9ed427ae2e.png">

3. I didn't see the blue question mark to the right of my username in the [guide](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user)
<img width="1037" alt="cla_details" src="https://user-images.githubusercontent.com/37377780/77109908-2237a000-69fb-11ea-9ba0-f236e19d10c6.png">

Please help. Thanks.

**Comment by ibakshay** [comment]
Hi @luchua-bc  , Thank you very much for reaching out to us. 
 It looks like this commit **"Address sensitive info logging"**  is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) to GitHub which you used for this commit in your local git configuration.

<img width="760" alt="Screenshot 2020-03-20 at 08 38 57" src="https://user-images.githubusercontent.com/33329946/77144607-a1be8100-6a86-11ea-85d4-beb264b7d024.png">

**Comment by KharitonOff** [comment]
@luchua-bc here is the email address, you have used for the commits: luchua@security-ho.us-east4-a.c.second-pier-239610.internal

**Comment by luchua-bc** [comment]
Thanks a lot @KharitonOff. The issue was resolved after I changed the email associated with my commit.
