### ISSUE TITLE
license/cla Pending — Contributor License Agreement is not signed yet.

### ISSUE THREAD

**Issue by cdbitz** [cla-assistant/cla-assistant#550]
URL to the linked Repo/Org:
https://github.com/Comcast/kuberhealthy

Steps to reproduce the problem:

1. sign cla with legal name instead of email
2. submit
3. PR shows license/cla pending
4. signature unable to be changed

What is the expected result?
accept signature, show error as invalid string, or add text instructing the signature format req'd

What happens instead?
signature text box is locked with presumably invalid signature for github user, project owner unable to merge fork

**Comment by KharitonOff** [comment]
Your signature is valid. CLA assistant doesn't change the status because you have signed the PR as @cdbitz but not as @chadbitzer . CLA assistant expects that the **committer** signs the CLA, not the author of the PR. In your case you (@cdbitz) are the author of the PR and @chadbitzer is the committer.

**Comment by cdbitz** [comment]
Very helpful lead, hadn't noticed that, thank you @KharitonOff !
