### ISSUE TITLE
GITHUB_ADMIN_USERS enforcement question.

### ISSUE THREAD

**Issue by chrisgavin** [cla-assistant/cla-assistant#551]
Hi!

I've got a question about the `GITHUB_ADMIN_USERS` configuration option. I've recently had a report that it's possible to bypass this restriction on a CLA Assistant instance that I support.

Indeed looking at the original implementation in #208, the only thing this option does is decide whether you should be redirected to `/auth/github?admin=true` or not. A user can just manually navigate to this URL themselves to affect whether they will be logged in as an admin or not.

My feeling is that this isn't really a security issue, as users only have access to manage repositories they are already an admin on, but I did find the behavior a bit surprising. Is this the intended behavior or should `GITHUB_ADMIN_USERS` be enforced in more places such as the API endpoints for setting up CLA Assistant on new repositories?

---

Thank you for making the CLA Assistant tool! It's really useful. :)

**Comment by KharitonOff** [comment]
@chrisgavin thank you for your positive feedback! It motivates us even more to support the open source community with our tools!

Your understanding of this option is right. This was introduced for those companies that host their own instances and want to restrict access to the admin ui. To be honest I don't remember whether I've tried to sign in by using the url directly...

As you mentioned, the users can take changes on this screen only for those repositories, for which they have push rights (members and admins) and for the organisations, for which they have admin rights. There is a possibility that users with write access rights to a repo unlink the repo by accident, it happened to us once already. In order to prevent such accidents and allow only certain users maintain settings of CLA assistant you can use this configuration option.

**Comment by chrisgavin** [comment]
Ah, perfect! Thank you for confirming my initial feelings. I'm glad it's not an issue.
