### ISSUE TITLE
Cannot link cla to a repo

### ISSUE THREAD

**Issue by kinosang** [cla-assistant/cla-assistant#558]
URL to the linked Repo/Org: github.com/JoyMoe/GalaScript/

Steps to reproduce the problem:

1. try link the repo with any CLA gist
2. it shows linked successfully

What is the expected result?
The CLA should be linked and works well.

What happens instead?
a. the dashboard shows webhook is not ready (so I create the webhook manually and re-try step 1~2)
b. refresh the dashboard, the repo disappeared (even when I created the webhook)
c. open https://cla-assistant.io/JoyMoe/GalaScript, it shows no CLA error

**Comment by michael-spengler** [comment]
Hi Kinosang.

Solution Proposal:
Unlink and relink the repository - so that the CLA Assistant will automatically create the correct webhook.

Background:
Perhaps there had been some network issues.

Question:
Could you provide a link to your repo? If the given solution proposal would not work, we could check the corresponding DB entry...

Kind regards
Michael

**Comment by kinosang** [comment]
@michael-spengler in fact, it's not a problem about the webhook.

The link cannot be stored, I can add the link, but it disappears from the dashboard after reloading the page.
