### ISSUE TITLE
Keep getting Contributor License Agreement is not signed yet

### ISSUE THREAD

**Issue by tvalasek** [cla-assistant/cla-assistant#562]
URL to the linked Repo/Org: https://github.com/argoproj/argo-events/pull/608

Steps to reproduce the problem:

1. After I sign the CLA I keep getting I need to sign CLA over and over again

What is the expected result?

What happens instead?

**Comment by michael-spengler** [comment]
@tvalasek: The reason is that github could not connect your account with the commit as you probably did not set the eMail via git config... properly yet.

So I guess this is a duplicate to: https://github.com/cla-assistant/cla-assistant/issues/548#issuecomment-601570984 

The reason why I come to this conclusion can be seen in the screenshot... attached
![Screen Shot 2020-04-27 at 13 12 41](https://user-images.githubusercontent.com/43786652/80366188-1d32ff80-8889-11ea-9795-a5bfa5442692.png)

**Comment by michael-spengler** [comment]
if this does not solve the issue feel free to reach out to us again.

**Comment by tvalasek** [comment]
You right, my local GH profile was using email address that wasn't set up in remote GH profile. Thanks!
