### ISSUE TITLE
option to skip signing for exempt contributions

### ISSUE THREAD

**Issue by binford2k** [cla-assistant/cla-assistant#572]
In some cases, signing the CLA is not required. For example, patches that are so non-substantive that they would not amount to an “original work of authorship” pursuant to the Section 102 of the United States Copyright Act, for those bound by US law.

See [our CLA preamble](https://gist.github.com/puppet-cla-assistant/7732a271a3ad9e99c49c7db3456b7249) for a more complete example.

I would like cla-assistant to check the gist for a file named `exempt.md` and then present both a link to read the full exemption policy and a button to skip signing for this pull request only. 

If the CLA is skipped, then I'd like the PR badge updated to `[CLA|exempt]`

This would not record anything in the database and it would be up to the project maintainers to allow the exemption or not.

**Comment by KharitonOff** [comment]
The exemption policy sounds reasonable. I like the idea. We've got also a contribution from Microsoft couple years ago, going in similar direction: you can define the minimal number of lines and/or minimal number of files in a PR as a threshold for CLA assistant to request agreement with your CLA. If the changes in a particular PR doesn't reach the 'threshold' CLA assistant reports green status "All CLA requirements met".
If you would like to extend this feature, feel free to contribute! We are happy to help you if you need some guidance or any other help from our side.

**Comment by binford2k** [comment]
This seems like a lot of code just to allow bypassing the CLA.... https://github.com/cla-assistant/cla-assistant/commit/28fe5c8eafb874a83d01a18b4aebadfce880ab39

**Comment by KharitonOff** [comment]
Yes, the function from Microsoft is designed in a way, where CLA assistant decides whether the PR is significant or not. As I understand your description you would like to let the contributor to decide whether s/he wants to sign your CLA or rather state her/his contribution as "non-substantive". 
In this case I believe it could work similar to our custom fields feature...
In order to...

>  check the gist for a file named `exempt.md`

You can use this function like we did it for the file named `metadata`. The condition here would be, that the file `exempt.md` is stored in the same gist together with CLA (see our description how to use custom fields on Readme)
https://github.com/cla-assistant/cla-assistant/blob/6d8958714a37edf2ac0e969dd5092d95dafc87b2/src/server/api/cla.js#L436-L457

I can imagine that you do something like this 
```
     const exemptPromise = files && files.exempt ? markdownRender(files.exempt.content, renderToken) : undefined 
     const data = await Promise.all([contentPromise, metaPromise, exemptPromise]) 
     gistContent.exempt = data[2] ? data[2].raw : undefined
```
>  present both a link to read the full exemption policy and a button to skip signing for this pull request only.

here we access the data on the client side and put the flag `hasCustomFields`to true or false
https://github.com/cla-assistant/cla-assistant/blob/6d8958714a37edf2ac0e969dd5092d95dafc87b2/src/client/services/utils.js#L39-L45

and based on the flag you can then adjust the UI
https://github.com/cla-assistant/cla-assistant/blob/6d8958714a37edf2ac0e969dd5092d95dafc87b2/src/client/controller/cla.js#L81

https://github.com/cla-assistant/cla-assistant/blob/6d8958714a37edf2ac0e969dd5092d95dafc87b2/src/client/templates/cla.html#L21


I hope this helps.
