### ISSUE TITLE
Sign CLA on first issue interaction?

### ISSUE THREAD

**Issue by larseggert** [cla-assistant/cla-assistant#579]
Is it possible to configure cla-assistant to prompt a user to sign the CLA when they first open a new issue or first comment on an existing one?

(Background: we're increasingly using repos for IETF work, where issue discussion replaces email discussion, and it would be great if we had an active indication that a participant had acknowledged the [IETF Note Well](https://ietf.org/about/note-well/).)

**Comment by KharitonOff** [comment]
yes and no :)
No - this is a pretty unique use case and CLA assistant doesn't support it our of the box. 
Yes - CLA assistant is an open source project, you can fork the source code, modify it accordingly and spin up your own instance. Code wise this should not be a big deal. You just need to add an additional webhook event, which triggers CLA assistant on new issue or issue comment and check the signature of the issue author or comment author instead of PR committer. All this information is accessible via GitHub API, you just need to adjust the CLA assistant's logic accordingly.
