### ISSUE TITLE
Suggestion: limit CLA assistant to a single org

### ISSUE THREAD

**Issue by vbasem** [cla-assistant/cla-assistant#585]
Let me thank you before I go in to a rant for the awesome tool you guys have made available to the world :1st_place_medal: 

As I explore the possibilities of CLA assistant on prem for my company, I noticed that an admin could still link his/her own private repos and orgs to the CLA assistant.

Suggestion: make it possible to limit the linkable  repos to a single org which is pre-configured when starting the server. 

If that is something that tickles everyones fancy, I can try and implement it.

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by KharitonOff** [comment]
Thank you very much for your positive feedback!

What kind of issue do you see if an admin would decide to use your instance for linking CLA with his private repos?

**Comment by vbasem** [comment]
Although I trust the admins not to do so, what happens is when the admin logs in, he is then given the choice of his/her own repos/orgs on top of the target organization. 

Now specific to my use case, I expected about 20-30 admins for different departments. It would serve the purpose better if the drop down of the repository is the one they are managing, rather than scrolling through all available options.

Another reasoning I could provide is the following:
If a company decides to use CLA assistant, it is very likely doing so for its own org/projects. It would be fair to assume that this option would be viable for majority of self hosted CLA assistants. Otherwise your instances does really the trick!

**Comment by KharitonOff** [comment]
I understand 😃  
How would you distinguisch between "target organizations" and repos and their private repos/orgs?

**Comment by vbasem** [comment]
A very simple approach perhaps would be to start the cla server with the org names parameter (similar to admin users)

```--GITHUB_ORGS=foo,bar```

Afterwards we can filter the viewed repos/orgs based on the provided  parameters. This approach requires nothing fancy.

**Comment by KharitonOff** [comment]
Ok, this could work 😃  You just need to restart the instance every time, when a new org is created.

**Comment by vbasem** [comment]
> Ok, this could work 😃 You just need to restart the instance every time, when a new org is created.

True that, but considering the use case that this CLA server is being setup for a specific company, you would expect it to be rather static. If we expect this to be a common case, then it makes sense to integrate this sort of feature into the dashboard itself!

**Comment by AveryRegier** [comment]
I'll add that if a company is hosting cla-assistant, they are using it to capture information on who signed the CLA so that they can defend the license in court. This may require collecting additional information so that they contributor can be gotten hold of.  This may require collecting personally identifiable information.  EU law has certain restrictions on the protection of personal data.  This personal data needs to be pertinent just to the organization that set up the assistant.  Allowing non-approved organizations to use your hosted assistant means the wrong set of lawyers has access to the data for those non-approved organizations, and the organization that hosts the instance is also needing to protect or delete that PII too.
