### ISSUE TITLE
Annulment of signed CLAs

### ISSUE THREAD

**Issue by vbasem** [cla-assistant/cla-assistant#606]
We are considering  developing  and adding a dashboard for users that have signed a CLA through the cla-assitant, through which they can view their signed CLAs and cancel them.

The workflow would consist of:

(1) User goes to CLA-ASSITANT and click on my signed CLAs
(2) User sees a list of repos/orgs and which CLAs he/she had signed with them
(3) User clicks on a specific signed CLA and selects ANNUL  (with confirmation)
(4) We remove the information that the user has an active signed CLA with the selected repo/org
(5) We keep some information that the user had previously signed the CLA from date - to date

Would you consider incorporating this feature back into the upstream project?

Reasoning: due to GDPR we are required to remove saved information from the database (after X years) upon cancellation of the CLA. Once a user retracts his/her agreement to a CLA, any future contributions will require re-signing of the CLA. This is currently not an option in the cla-assitant.

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by KharitonOff** [comment]
Sounds very interesting!
We have started developing similar feature/view couple years ago, but were never able to finish it. It is accessible via cla-assistant.io/my-cla url, but it's not a functional one.  Maybe you'd like to review the code and adjust according to your needs...

Here is the ui controller, which is a good starting point of tracking the code: https://github.com/cla-assistant/cla-assistant/blob/master/src/client/controller/my-cla.js 

Following issue would navigate you to the api endpoint, for termination user's signature https://github.com/cla-assistant/cla-assistant/issues/406

And one more thing I want to point you to: There is an API for retrieving user's signatures: /api/cla/getSignedCLA, which was designed for this feature. 
https://github.com/cla-assistant/cla-assistant/blob/83cea5561f3c8c2952afa417d0c2935c6f3ed0f9/src/server/services/cla.js#L612
But it needs to be refactored. We should remove the query parameter “user” from it’s payload and use the user name from the authentication process. In this case we will only provide a list of CLAs that belongs to the requestor. Otherwise you can retrieve information for any project contributor, which is unacceptable from data privacy point of view.

This API is currently disabled. All CLA assistant’s API calls are processed in the authentication middleware (https://github.com/cla-assistant/cla-assistant/blob/e5e68443e3b64f9aa7886cfb54fa5d32ef77a7f8/src/server/middleware/authenticated.js#L67). At this point we accept only API calls, which are predefined in the configuration file config.js (https://github.com/cla-assistant/cla-assistant/blob/e5e68443e3b64f9aa7886cfb54fa5d32ef77a7f8/src/config.js#L86). Since this API is not in the list, CLA assistant responds with status 401 'Authentication required' and doesn’t process the request further.

I hope this information is helpful for you.

**Comment by vbasem** [comment]
@KharitonOff wow, awesome. Seems some of the work was done here already. Due to vacation time, we will probably start working on this in September. Now that I have a solid lead, it will certainly speed things up.

We can either close the issue and follow up further discussion in future issues, or leave this for clarifications that will follow.

What do you think?

**Comment by KharitonOff** [comment]
Let's keep it open. Our stale bot will try to close it, but it's not a big deal, we will tell him too that we want keep it open 😃

**Comment by augustoproiete** [comment]
Keep open stale-bot :)

**Comment by vbasem** [comment]
We have started implementing the logic for revoke and hopefully we can review it with you soon.

**Comment by vbasem** [comment]
@KharitonOff initial PR for this seems to do the job

**Comment by michael-spengler** [comment]
@ibakshay: What would be the GitHub Action based (https://github.com/cla-assistant/github-action/blob/master/README.md) way to deal with such things or are those challenges not relevant at all there?

I see a rapidly growing number of people are using rather the "lightweight CLA handling" (https://github.com/cla-assistant/github-action/blob/master/README.md) and I wonder if it is a good idea to add such features to the "old school CLA Assistant".
