### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by belliash** [cla-assistant/cla-assistant#612]
Would it be possible to support some a self-hosted Git solutions like Gogs or Gitea?

**Comment by KharitonOff** [comment]
No, unfortunately not. We fully rely on GitHub's processes and APIs. A whole bunch of source code logic needs to be rewritten and adjusted in order to be able to support other platforms.
But we are always open for new ideas and contributions! In case you'd like to take the challenge, we will do our best in order to provide you as much help as possible.
