### ISSUE TITLE
Consequences of renaming the GitHub account used to sign into cla-assistant?

### ISSUE THREAD

**Issue by dltj** [cla-assistant/cla-assistant#614]
URL to the linked Repo/Org:  https://github.org/folio-org

For historical reasons, we started with @folio-org-cla as the account tied to the cla-assistant system.  The FOLIO project, though, has become part of a bigger effort—the Open Library Foundation—and we would like to widen the scope of our use of cla-assistant to cover the other projects in the foundation.  Do you know what the effect on current signators would be if we renamed `folio-org-cla`→`olf-org-cla`?  Would we lose access to the current list of signators?  Would current signators be asked to re-sign?  (Any other gotchas I might be missing?)

**Comment by KharitonOff** [comment]
This shouldn't be a problem as far I know. We have an issue with renamed accounts, that the user's "old" signatures doesn't get recognized if s/he opens a PR with changed name...
In your case, this is irrelevant, because @folio-org-cla doesn't open any PR in it's name :) The list of signators is not connected to the user, who has set up CLA, hence there won't be any implications on the signatures or linked lists. The only possible side effect I can imagine is that you will need to provide the authorisation scopes on CLA assistant again (just log into the CLA assistant and provide authorization scope for the orgs as well, if needed).

**Comment by dltj** [comment]
Thank you for the quick reply.  That gives me confidence to give it a try and report back if there are issues.
