### ISSUE TITLE
hook running, but not doing anything

### ISSUE THREAD

**Issue by kwquick** [cla-assistant/cla-assistant#63]
I setup a test repository (kwquick/test_cla) and it's identified as status green (everything is ok) for cla-assistant, and I see the hook, but a non-confirmed client doesn't see prompts and I don't see any indications in the pull request that they have not confirmed the cla.  Can you help identify what is wrong?  I can grant you access to this test repo if needed.

**Comment by KharitonOff** [comment]
Hi Kevin,
the problem here is, that the committer of both pull requests is not a github user. CLA assistant doesn't cover this use case yet. 
Definitely there should be at least a notification from the CLA assistant that this committer hasn't sign the CLA. We will probably not provide a possibility to sign a CLA without a github account, but we'll fix the notification logic.
I suppose that if aztsmith changes his/her e-mail to the same one he/she used in the commits then github (and CLA assistant also) will identify him/her as the committer of the pull requests.

**Comment by kwquick** [comment]
Hi Anton,

That was indeed the problem, and when my test committer associated his email with his github account it started working just fine.

I agree that getting signatures from non-github-accounts is probably out of scope, but having a notification of the issue on the pull request would definitely be nice.

Thanks, and I'm enjoying the cla-assistant!

**Comment by KharitonOff** [comment]
should be solved via 0efa36ff24b7baa43ca8693aec14b2367a7481fd
