### ISSUE TITLE
Status still pending after agreement

### ISSUE THREAD

**Issue by LBakkerTDS** [cla-assistant/cla-assistant#662]
URL to the linked Repo/Org:

Steps to reproduce the problem:

1.
2.
3.

What is the expected result?

What happens instead?

**Comment by ibakshay** [comment]
Could you please retrigger the CLA check by using this API as mentioned here - https://github.com/cla-assistant/cla-assistant/issues/520#issuecomment-571590565 ?

**Comment by LBakkerTDS** [comment]
Hi,

 

I am not sure what to fill in for the organization name, since I’m not a member of any…

 

Kindest,

Linda

 

Van: Akshay Iyyadurai Balasundaram <notifications@github.com> 
Verzonden: dinsdag 16 februari 2021 16:28
Aan: cla-assistant/cla-assistant <cla-assistant@noreply.github.com>
CC: L. Bakker <lbakker@tds-info.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [cla-assistant/cla-assistant] Status still pending after agreement (#662)

 

Could you please retrigger the CLA check by using this API as mentioned here - #520 (comment) <https://github.com/cla-assistant/cla-assistant/issues/520#issuecomment-571590565>  ?

**Comment by lmbakker** [comment]
It seems that I’ve agreed the CLA with another user name (‘LBakkerTDS’) where it should have been ‘lmbakker’. I have changed my user name to ‘lmbakker’.

 

Could you please send the CLA link again, so that I can resign it with the proper user name? Thanks a lot!

 

Van: Akshay Iyyadurai Balasundaram <notifications@github.com> 
Verzonden: dinsdag 16 februari 2021 16:28
Aan: cla-assistant/cla-assistant <cla-assistant@noreply.github.com>
CC: L. Bakker <lbakker@tds-info.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [cla-assistant/cla-assistant] Status still pending after agreement (#662)

 

Could you please retrigger the CLA check by using this API as mentioned here - #520 (comment) <https://github.com/cla-assistant/cla-assistant/issues/520#issuecomment-571590565>  ?

**Comment by ibakshay** [comment]
Could you please send the link to the repository where you are facing issue with CLA assistant ?

**Comment by lmbakker** [comment]
https://github.com/rdkcentral/Lightning-SDK

 

 

Van: Akshay Iyyadurai Balasundaram <notifications@github.com> 
Verzonden: dinsdag 16 februari 2021 19:29
Aan: cla-assistant/cla-assistant <cla-assistant@noreply.github.com>
CC: lmbakker <lbakker@tds-info.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [cla-assistant/cla-assistant] Status still pending after agreement (#662)

 

Could you please send the link to the repository where you are facing issue with CLA assistant ?

**Comment by LBakkerTDS** [comment]
Hi, there is no need to take action on this issue anymore. The problem was an inconsistent user name and email address.

 

Kind regards,
Linda

 

Van: Akshay Iyyadurai Balasundaram <notifications@github.com> 
Verzonden: dinsdag 16 februari 2021 19:29
Aan: cla-assistant/cla-assistant <cla-assistant@noreply.github.com>
CC: lmbakker <lbakker@tds-info.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [cla-assistant/cla-assistant] Status still pending after agreement (#662)

 

Could you please send the link to the repository where you are facing issue with CLA assistant ?

**Comment by ibakshay** [comment]
Thanks so much for informing us. Then I will close this issue.
