### ISSUE TITLE
CLA sign is required only for Mallikarjuna54 

### ISSUE THREAD

**Issue by mallikarjuna54** [cla-assistant/cla-assistant#668]
URL to the linked Repo/Org:  https://github.com/rdkcentral/RDKSplashScreen/pull/7

Steps to reproduce the problem:

1.
2.
3.

What is the expected result? "Mallikarjuna54"user id enough to CLA signed. Other id please remove.

What happens instead? here 2 user id's are registered instead of one.

**Comment by ibakshay** [comment]
Hi @mallikarjuna54,
Unfortunately, all the users involved in the pull request should sign the CLA. 

Also please note. It looks like this commit "BD-909:Relicense RDKSplashScreen to Metrological Apache" from **Mallikarjuna Masina** is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) which you used for this commit in your local git configuration.
<img width="1272" alt="Screenshot 2021-03-11 at 12 14 02" src="https://user-images.githubusercontent.com/33329946/110779654-15433a80-8264-11eb-9dbb-be5902d672b0.png">

**Comment by mallikarjuna54** [comment]
> Hi @mallikarjuna54,
> Unfortunately, all the users involved in a pull request should sign the CLA.
> 
> Also please note. It looks like this commit "BD-909:Relicense RDKSplashScreen to Metrological Apache" from **Mallikarjuna Masina** is not recognised by GitHub because [you need to add the email address](https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user) which you used for this commit in your local git configuration.
> <img alt="Screenshot 2021-03-11 at 12 14 02" width="1272" src="https://user-images.githubusercontent.com/33329946/110779654-15433a80-8264-11eb-9dbb-be5902d672b0.png">

HI ibakshay ,

Mallikarjuna54 as signed already in local git as well as Registered in git hub. So in Pull request please remove extra user (*Mallikarjuna Masina*) so that my commit will ready to merge.

**Comment by ibakshay** [comment]
>So in Pull request please remove extra user (Mallikarjuna Masina) so that my commit will ready to merge.
You have to reach out to the project admin for this query. 

Note: CLA assistant tool expects all the contributors in a Pull Request to sign the CLA.

**Comment by Shegox** [comment]
Hi @mallikarjuna54, 

seems like the problem was resolved. I'm going a head and close this issue. If you have further questions/issues please feel free to open a new issue. Many thanks.
