### ISSUE TITLE
migrating to cla-assistant

### ISSUE THREAD

**Issue by jdanyow** [cla-assistant/cla-assistant#67]
Related to https://github.com/cla-assistant/cla-assistant/issues/66

When migrating to CLA assistant we'd like to pre-fill the list of CLA signers.  Is this possible?

**Comment by EisenbergEffect** [comment]
We are very interested in using cla-assistant for Aurelia. Currently, we have a Google doc with a list of community members who have already signed our CLA. Basically, it's a list of email addresses. We would like to be able to import this list into cla-assistant so that we don't have to ask everyone to re-sign the CLA and so that we don't have to track signatures across two data sources for historical reasons.

**Comment by KharitonOff** [comment]
Hi, glad to hear that you are interested in CLA assistant :smile: . We are thinking about implementation of  an import functionality. 
CLA assistant integrates completely into GitHub workflow and identifies committers by their GitHub account now. That means that a list of email addresses would not be enough yet. We'll keep in mind your use case by further implementation and we'll try to cover it.

**Comment by benboeser** [comment]
I am sure you have noticed already. But the import feature is available under: 
![screen shot 2016-01-22 at 9 27 46 am](https://cloud.githubusercontent.com/assets/4432507/12517970/7d656c6e-c0ea-11e5-93fc-89178172523d.png)

**Comment by thojansen** [comment]
This is based on a list of github users (not emails).

**Comment by thojansen** [comment]
Closing this issue and opening #98 for importing emails instead of GitHub users (which is already possible)
