### ISSUE TITLE
Signing CLA with 2 users (same account)

### ISSUE THREAD

**Issue by aanogueira** [cla-assistant/cla-assistant#677]
Hello,

After signing the CLA I get this message:

![image](https://user-images.githubusercontent.com/28967377/115202571-6f021480-a0ee-11eb-806d-69adbeab1693.png)

The first one is my username and the second one is my name.
Am I missing something?

URL: https://github.com/vectorizedio/redpanda/pull/1191

Steps to reproduce the problem:

1. git config --global user.name "$NAME"
2. git config --global user.email "$EMAIL"
3. git commit --amend --author="$NAME <$EMAIL>"
4. git push --force $REPO $BRANCH

**Comment by KharitonOff** [comment]
If you compare these two commits:
https://github.com/vectorizedio/redpanda/pull/1191/commits/e127274739b675f0c2e76aafca55139a5ab73ad7
and 
https://github.com/vectorizedio/redpanda/pull/1191/commits/53cb3d8937a4b21e337c825ad2e32d2f0cbcbc8f
Then you'll see that GitHub doesn't recognize your user in the first one, but in the second one. 

You use different emails in those commits: https://api.github.com/repos/vectorizedio/redpanda/pulls/1191/commits
You should put both email addresses into your github account in order to make GitHub able to assign both commits to the same user.

**Comment by aanogueira** [comment]
@KharitonOff thank you for your reply!
I didn't noticed that my other email was also being used...

I've added the one email missing.

Do I need to sign it once again?

**Comment by aanogueira** [comment]
After adding the missing email address the issue was solved.
