### ISSUE TITLE
After I've successfully signed the CLA still get "not signed yet"

### ISSUE THREAD

**Issue by cgrail** [cla-assistant/cla-assistant#68]
For the PR I've signed the CLA and I get a success message. But the CLA status doesn't change.
https://github.com/SAP/sap.github.com/pull/8
but worked for:
https://github.com/SAP/BUILD/pull/27

**Comment by KharitonOff** [comment]
Hi Christian,
the only thing you need to do is to add the e-mail address you used in your commit https://github.com/cgrail/sap.github.com/commit/09f797481bf4a1deb63c37b60a9324ed6a7ed3d8 to your github account. GitHub and CLA assistant so can not recognize you as a committer.

**Comment by cgrail** [comment]
@KharitonOff Thanks for your help. This fixed the issue.
But shouldn't you also fix your code? I mean there should be at least an error message which states that the E-Mail addresses don't match. All I got was a success message.

**Comment by KharitonOff** [comment]
Yes, you're right, we should make it clearer what's wrong with such PRs.
We can make it more transparent writing an info into the PR-comment. Something like: "The committer XY seems not to be a GitHub user. XY needs a GitHub account in order to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account ([for further information, click here] (https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user)). "

**Comment by cgrail** [comment]
:+1: great

thanks

**Comment by thojansen** [comment]
:+1:
