### ISSUE TITLE
Missing CLA contributors

### ISSUE THREAD

**Issue by xfalcox** [cla-assistant/cla-assistant#802]
## URL to the linked Repository or Organization

https://github.com/discourse/discourse

## Steps to reproduce the problem

1. Log into https://cla-assistant.io/
2. Tries to check the Contributors list
3. Link to the list is gone

## What is the expected result?

I can check my contributors list

## What happens instead?

There is no link

## Any other information? (attach screenshot if possible)

![image](https://user-images.githubusercontent.com/1385470/142254120-af98f1b6-b007-4d21-be3e-31680fb87b5f.png)

## Used browser and browser version?

Latest Firefox

**Comment by xfalcox** [comment]
Also worth noting that trying to obtain the contributor list via the API is failing. This used to work at least until August 23.

```
curl 'https://cla-assistant.io/api/cla/getAll' -s -H 'Content-Type: application/json;charset=utf-8' -H 'X-Token: mytoken'  --data '{"repoId":"7569578","gist":{"gist_url":"https://gist.github.com/eviltrout/1fdf99d0500ed1b922057797c222c3b7","gist_version":"6c4ef486b56614a4ec60716d8ef1f2e01f1c5bce"},"sharedGist":false}'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

**Comment by Shegox** [comment]
I'm currently traveling and can take an in-depth look on Monday.

Can you as well please take a look at the network calls (should be in the network tab of your browsers development tools) and if they fail, get me the x-trace something header and I can crosscheck our logs.

Many thanks already in advance.

**Comment by xfalcox** [comment]
```
< HTTP/2 500 
< x-powered-by: Express
< x-cloud-trace-context: 888d860d336d3845e94ebbc35d1eb828/2450498112193925715;o=1
< x-frame-options: Deny
< x-content-type-options: nosniff
< content-security-policy: default-src 'none'
< content-type: text/html; charset=utf-8
< set-cookie: redacted Path=/; Expires=Wed, 17 Nov 2021 19:06:02 GMT; HttpOnly; Secure
< date: Wed, 17 Nov 2021 18:06:02 GMT
< server: Google Frontend
< content-length: 148
```

Thanks for the prompt response @Shegox. Is there a possibility all data is lost?

**Comment by Shegox** [comment]
Unlikely and we have backups going back a couple of months at least. But let me check this on Monday in detail as I only have a mobile phone here. :)
Hope that is okay.

**Comment by xfalcox** [comment]
Thanks @Shegox ! Hope you enjoy your travel!

**Comment by Shegox** [comment]
Quick update: 
- Unfortunately the log files didn't really help. They just showed the 5xx error response code.
- However I cross checked the database manually and all data is there. So it is just a frontend problem.

If you need it urgently I can get you a database export, otherwise I will try to get it working again. 

In the meantime, can you try a different browser and/or resetting your cookies please to check if maybe reauthentication helps? Thanks a lot

**Comment by xfalcox** [comment]
> If you need it urgently I can get you a database export, otherwise I will try to get it working again.

Can you please send the JSON export to `rafael@discourse.org` ? Thanks!

> In the meantime, can you try a different browser and/or resetting your cookies please to check if maybe reauthentication helps? 

Just did it and the contributors list is still empty :cry:

**Comment by Shegox** [comment]
I just sent them to you now. 

I would like to anyway try to figure out the problem. Would it possible for you to ask someone else in the team (with at best admin permissions to the discourse/discourse repo) to log into cla-assistant and see if they can see the signatures? 
If not can they as well check the browser network tool and give the `x-cloud-trace-context` of the failed responses. 

My current guess is that because discourse has many signatures (2k+) this causes problems.

**Comment by xfalcox** [comment]
> with at best admin permissions to the discourse/discourse repo

This nailed it!

I lost admin permissions on the discourse/discourse repo, that is why I can't see nor download the signed list anymore.

Sorry for the noise :bow:

**Comment by Shegox** [comment]
This is very weird, because it should normally check for `push` permissions and not admin permission 🤔

Or even if that is the case it shouldn't show you the linked repo in the first place.
