### ISSUE TITLE
Signed CLA but the Status Is Not Updated Even After the Recheck

### ISSUE THREAD

**Issue by xiaofenhappy** [cla-assistant/cla-assistant#818]
## URL to the linked Repository or Organization

https://github.com/gardener/terraformer/

## Steps to reproduce the problem

I've signed the CLA, but in the [PR](https://github.com/gardener/terraformer/pull/114), it still shows the CLA is not signed. I tried retriggering the check with the URL
https://cla-assistant.io/check/gardener/terraformer/?pullRequest=114, but no help.

## What is the expected result?

The status gets updated.

## What happens instead?

The CLA status is not updated

## Any other information? (attach screenshot if possible)
![image](https://user-images.githubusercontent.com/25812529/147624885-6505d4b4-2367-4627-9bc5-70d107d09e5d.png)

**Comment by Shegox** [comment]
Hi @xiaofenhappy, thanks for opening the issue. 

The problem is actually that in your PR the PR author and commit author are two different GitHub users (PR: @xiaofenhappy, commit: @molecule-z) and for CLA-Assistant to mark a PR as signed both need to accept the CLA. 
The commit author is determined based on the used email address (you can see it [in the raw patch](https://github.com/gardener/terraformer/commit/a5aec571b0b324155aa1651ffd617492156dda23.patch)) and this email address is not associated with your GitHub account and thus needs a separate signature.
To solve this there are two ways:
- You can adjust the commit email address and force push the branch to update the author to your own email address. (Details on how to fix this at [why-are-my-commits-linked-to-the-wrong-user#commits-are-linked-to-another-user](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-linked-to-another-user))
\- or - 
- Login to @molecule-z and sign the CLA with that account as well.

**Comment by xiaofenhappy** [comment]
@Shegox Yep, that's the reason.
It works, thanks.
