### ISSUE TITLE
cla text not showing

### ISSUE THREAD

**Issue by subhasisb** [cla-assistant/cla-assistant#838]
Hi, 

we  use cla-assistant for https://github.com/openpbs/openpbs. When i go into the cla-assistant link for any open PR, it shows an empty screen (and not the cla text). 

Also, while the dashboard page shows that 57 persons have signed the CLA (see screenshot):
![image](https://user-images.githubusercontent.com/15310678/153336238-80d6721d-8311-4e96-8f58-e174513b66ec.png)

whereas on clicking the link of the persons signed (57), it shows 0 persons have signed the CLA (any version i choose):
![image](https://user-images.githubusercontent.com/15310678/153336467-f92b5b12-eaec-497a-9b22-e310570e5f53.png)

**Comment by giuliobenetti** [comment]
I have the same problem, following

**Comment by giuliobenetti** [comment]
@subhasisb I've fixed the CLA not showing. My problem was due to the fact I've first registered to Github using one e-mail, then I've added a new one and switched to it as my main e-mail. To fix the problem I have:
1) removed old e-mail
2) re-inserted old e-mail(because I still need it)
That fixed the problem with CLA showing.

**Comment by subhasisb** [comment]
@giuliobenetti  thanks for the tip. However in my case, my email stayed the same, so not the same issue. That said, the problem disappeared by itself, making me think that it was probably a temporary service disruption...
