### ISSUE TITLE
CLA is empty

### ISSUE THREAD

**Issue by StenGruener** [cla-assistant/cla-assistant#842]
Hello, I cannot sign this CLA: https://cla-assistant.io/admin-shell-io/aasx-server?pullRequest=96 the page is just empty.

**Comment by Shegox** [comment]
Hi @StenGruener, 

can you provide a bit more details please (at best a screenshot). What exactly is empty on the page for you?

I assume the CLA text is not shown, right? This might have been a temporary issue, due to depleted rate limits by the user having it configured.
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/16856448/154038407-55d4ffc6-7dd7-4268-b5e8-4fabbdfbcda9.png">

**Comment by StenGruener** [comment]
now it worked, seemingly a temporary issue
