### ISSUE TITLE
Multiple committers under same GitHub account aren't linked

### ISSUE THREAD

**Issue by Midorusha** [cla-assistant/cla-assistant#95]
I have multiple email addresses associated with my GitHub account. Once I completed signing, it only recognized my GitHub account and my primary email address. The two were coalesced under my GitHub name, but the other email address is still visible.

**Comment by KharitonOff** [comment]
Are you referring to https://github.com/PerfectlySoft/Perfect/pull/85?
It seems that the email address "midorusha@github.com" of the committer cdavis is not assigned to any GitHub account. Could you check please if it's also added to the list of your emails?

**Comment by Midorusha** [comment]
Yes, I am referring to that commit. The cdavis email address is also
associated with the midorusha@github.com account.

**Comment by KharitonOff** [comment]
Just because you are writing "with the midoruscha@github.com **account**" I think that you have misunderstood my question. Please excuse me if I'm wrong. I just want to be clear that we are using the same terms :) 
Your account Midorusha should have standard email address called "midorusha@users.noreply.github.com". That means if you use email address "midorusha@github.com" for your commits github doesn't associate it automatically with your Midorusha github account until you enter it in the list of your emails.
I see that github has recognized two other emails but not the mentioned one.

**Comment by Midorusha** [comment]
Ah I see the issue, midorusha@github.com was a mistake in the terminal. I was confusing cdavis with an email address and not a user name. Sorry about that. 

Can I just change the commit author and cla-assitant will pick up any changes?

**Comment by KharitonOff** [comment]
No problem, I'm glad that we've sold this issue. Yes, changing the commit author should work fine.
CLA assistant needs only to be triggered via a webhook (e.g. you can add a new commit to the PR or you just wait until somebody opens a new PR or the repository owner clicks on the "Recheck PRs" in CLA assistant) in order to reflect it on the PR.
