### ISSUE TITLE
Settings and Signature History for Repo Inexplicably Lost

### ISSUE THREAD

**Issue by posborne** [cla-assistant/cla-assistant#998]
## URL to the linked Repository or Organization

https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers

## Steps to reproduce the problem

Unknown

## Any other information? (attach screenshot if possible)

This repo was configured with a custom CLA and settings for allowing contributions from specific organizations a couple years ago and had been working as expected.  Unexpectedly, I received a report that the CLA was the SAP CLA rather than our own and confirmed that was the case.  Looking at the settings in cla-assistant.io for the repo I found the following:

1. The repo was still linked in cla-assistant.
2. The CLA was using the SAP CLA rather than the one configured and it appeared to be using default values.
3. Other settings such as orgs allowed to contribute without signing were no longer present.

After putting the settings back to correct values the signature history for the CLA is no longer available meaning that we are in a difficult situation involving contributors needing to agree to the CLA again and losing the desired direct audit trail of signatures that we would desire.  If at all possible, we would like to recover this.  This issue seems like it may, at some level, resemble portions of what is reported in https://github.com/cla-assistant/cla-assistant/issues/641 though the format of the gist used doesn't seem to be the problematic one reported there.

paul -dot- osborne @t smartthings -dot- com

**Comment by Shegox** [comment]
Hi 👋,

thats really bad to hear and should not occur. I'm looking into it.

Old signatures are not gone, however the last one I see for your specific gist is from `created_at: ISODate("2022-05-28T07:01:10.566Z")` .
I have to dig a bit into our backups to see if the data was lost somewhere else. 

One difference which I see is in the used `gist_url` the old one was `https://gist.github.com/8f788e58968774365661c1fd1c318938` (without a username) instead of `https://gist.github.com/stfwbuild/8f788e58968774365661c1fd1c318938`. Can you please try to set that as your CLA inside of cla-assistant and then the old signatures should show up again. 

About the actual problem of having the SAP CLA listed, do you any rough estimates when the SAP CLA started to get used or when the old one were still being used?

**Comment by Shegox** [comment]
Can you look now again? I manually modified the linked CLA to match the one without the username in the path.

**Comment by posborne** [comment]
> Can you look now again? I manually modified the linked CLA to match the one without the username in the path.

@Shegox I confirmed that the signatures prior to the date you mentioned are now visible in the tool and was able to download a backup of those.
